/* glw_gen.c -- GENERATED by tools/gen_glw.py; do not edit. */
#include "gl_worker_internal.h"

enum {
  GLW_OP_glActiveTexture = 1,
  GLW_OP_glAttachShader = 2,
  GLW_OP_glBeginQuery = 3,
  GLW_OP_glBindAttribLocation = 4,
  GLW_OP_glBindBuffer = 5,
  GLW_OP_glBindFramebuffer = 6,
  GLW_OP_glBindRenderbuffer = 7,
  GLW_OP_glBindTexture = 8,
  GLW_OP_glBlendEquation = 9,
  GLW_OP_glBlendEquationSeparate = 10,
  GLW_OP_glBlendFunc = 11,
  GLW_OP_glBlendFuncSeparate = 12,
  GLW_OP_glBufferData = 13,
  GLW_OP_glBufferSubData = 14,
  GLW_OP_glCheckFramebufferStatus = 15,
  GLW_OP_glClear = 16,
  GLW_OP_glClearColor = 17,
  GLW_OP_glClearDepthf = 18,
  GLW_OP_glClearStencil = 19,
  GLW_OP_glColor4f = 20,
  GLW_OP_glColorMask = 21,
  GLW_OP_glCompileShader = 22,
  GLW_OP_glCompressedTexImage2D = 23,
  GLW_OP_glCopyTexImage2D = 24,
  GLW_OP_glCopyTexSubImage2D = 25,
  GLW_OP_glCreateProgram = 26,
  GLW_OP_glCreateShader = 27,
  GLW_OP_glCullFace = 28,
  GLW_OP_glDeleteBuffers = 29,
  GLW_OP_glDeleteFramebuffers = 30,
  GLW_OP_glDeleteProgram = 31,
  GLW_OP_glDeleteRenderbuffers = 32,
  GLW_OP_glDeleteShader = 33,
  GLW_OP_glDeleteTextures = 34,
  GLW_OP_glDepthFunc = 35,
  GLW_OP_glDepthMask = 36,
  GLW_OP_glDepthRangef = 37,
  GLW_OP_glDisable = 38,
  GLW_OP_glDisableClientState = 39,
  GLW_OP_glDisableVertexAttribArray = 40,
  GLW_OP_glDrawArrays = 41,
  GLW_OP_glDrawElements = 42,
  GLW_OP_glEnable = 43,
  GLW_OP_glEnableClientState = 44,
  GLW_OP_glEnableVertexAttribArray = 45,
  GLW_OP_glEndQuery = 46,
  GLW_OP_glFinish = 47,
  GLW_OP_glFlush = 48,
  GLW_OP_glFramebufferRenderbuffer = 49,
  GLW_OP_glFramebufferTexture2D = 50,
  GLW_OP_glFrontFace = 51,
  GLW_OP_glGenBuffers = 52,
  GLW_OP_glGenFramebuffers = 53,
  GLW_OP_glGenQueries = 54,
  GLW_OP_glGenRenderbuffers = 55,
  GLW_OP_glGenTextures = 56,
  GLW_OP_glGenerateMipmap = 57,
  GLW_OP_glGetActiveAttrib = 58,
  GLW_OP_glGetActiveUniform = 59,
  GLW_OP_glGetAttachedShaders = 60,
  GLW_OP_glGetAttribLocation = 61,
  GLW_OP_glGetBooleanv = 62,
  GLW_OP_glGetBufferParameteriv = 63,
  GLW_OP_glGetError = 64,
  GLW_OP_glGetFloatv = 65,
  GLW_OP_glGetFramebufferAttachmentParameteriv = 66,
  GLW_OP_glGetIntegerv = 67,
  GLW_OP_glGetProgramInfoLog = 68,
  GLW_OP_glGetProgramiv = 69,
  GLW_OP_glGetQueryObjectuiv = 70,
  GLW_OP_glGetShaderInfoLog = 71,
  GLW_OP_glGetShaderSource = 72,
  GLW_OP_glGetShaderiv = 73,
  GLW_OP_glGetString = 74,
  GLW_OP_glGetUniformLocation = 75,
  GLW_OP_glGetVertexAttribPointerv = 76,
  GLW_OP_glGetVertexAttribfv = 77,
  GLW_OP_glGetVertexAttribiv = 78,
  GLW_OP_glHint = 79,
  GLW_OP_glIsEnabled = 80,
  GLW_OP_glIsFramebuffer = 81,
  GLW_OP_glIsProgram = 82,
  GLW_OP_glIsRenderbuffer = 83,
  GLW_OP_glIsTexture = 84,
  GLW_OP_glLineWidth = 85,
  GLW_OP_glLinkProgram = 86,
  GLW_OP_glMapBuffer = 87,
  GLW_OP_glPixelStorei = 88,
  GLW_OP_glPolygonOffset = 89,
  GLW_OP_glReadPixels = 90,
  GLW_OP_glRenderbufferStorage = 91,
  GLW_OP_glScissor = 92,
  GLW_OP_glShaderBinary = 93,
  GLW_OP_glShaderSource = 94,
  GLW_OP_glStencilFunc = 95,
  GLW_OP_glStencilFuncSeparate = 96,
  GLW_OP_glStencilMask = 97,
  GLW_OP_glStencilMaskSeparate = 98,
  GLW_OP_glStencilOp = 99,
  GLW_OP_glStencilOpSeparate = 100,
  GLW_OP_glTexCoordPointer = 101,
  GLW_OP_glTexImage2D = 102,
  GLW_OP_glTexParameterf = 103,
  GLW_OP_glTexParameteri = 104,
  GLW_OP_glTexParameteriv = 105,
  GLW_OP_glTexSubImage2D = 106,
  GLW_OP_glUniform1f = 107,
  GLW_OP_glUniform1fv = 108,
  GLW_OP_glUniform1i = 109,
  GLW_OP_glUniform1iv = 110,
  GLW_OP_glUniform2f = 111,
  GLW_OP_glUniform2fv = 112,
  GLW_OP_glUniform2i = 113,
  GLW_OP_glUniform2iv = 114,
  GLW_OP_glUniform3f = 115,
  GLW_OP_glUniform3fv = 116,
  GLW_OP_glUniform3i = 117,
  GLW_OP_glUniform3iv = 118,
  GLW_OP_glUniform4f = 119,
  GLW_OP_glUniform4fv = 120,
  GLW_OP_glUniform4i = 121,
  GLW_OP_glUniform4iv = 122,
  GLW_OP_glUniformMatrix2fv = 123,
  GLW_OP_glUniformMatrix3fv = 124,
  GLW_OP_glUniformMatrix4fv = 125,
  GLW_OP_glUnmapBuffer = 126,
  GLW_OP_glUseProgram = 127,
  GLW_OP_glVertexAttrib1f = 128,
  GLW_OP_glVertexAttrib1fv = 129,
  GLW_OP_glVertexAttrib2f = 130,
  GLW_OP_glVertexAttrib2fv = 131,
  GLW_OP_glVertexAttrib3f = 132,
  GLW_OP_glVertexAttrib3fv = 133,
  GLW_OP_glVertexAttrib4f = 134,
  GLW_OP_glVertexAttrib4fv = 135,
  GLW_OP_glVertexAttribPointer = 136,
  GLW_OP_glVertexPointer = 137,
  GLW_OP_glViewport = 138,
  GLW_OP_vglGetProcAddress = 139,
  GLW_OP_vglInit = 140,
  GLW_OP_vglInitExtended = 141,
  GLW_OP_vglSetupRuntimeShaderCompiler = 142,
  GLW_OP_vglSwapBuffers = 143,
  GLW_OP_GEN_COUNT
};
_Static_assert(GLW_OP_GEN_COUNT <= GLW_OP_CUSTOM_BASE, "generated ops overlap custom ops");

const char *const glw_op_names[GLW_OP_GEN_COUNT] = {
  "?",
  "glActiveTexture",
  "glAttachShader",
  "glBeginQuery",
  "glBindAttribLocation",
  "glBindBuffer",
  "glBindFramebuffer",
  "glBindRenderbuffer",
  "glBindTexture",
  "glBlendEquation",
  "glBlendEquationSeparate",
  "glBlendFunc",
  "glBlendFuncSeparate",
  "glBufferData",
  "glBufferSubData",
  "glCheckFramebufferStatus",
  "glClear",
  "glClearColor",
  "glClearDepthf",
  "glClearStencil",
  "glColor4f",
  "glColorMask",
  "glCompileShader",
  "glCompressedTexImage2D",
  "glCopyTexImage2D",
  "glCopyTexSubImage2D",
  "glCreateProgram",
  "glCreateShader",
  "glCullFace",
  "glDeleteBuffers",
  "glDeleteFramebuffers",
  "glDeleteProgram",
  "glDeleteRenderbuffers",
  "glDeleteShader",
  "glDeleteTextures",
  "glDepthFunc",
  "glDepthMask",
  "glDepthRangef",
  "glDisable",
  "glDisableClientState",
  "glDisableVertexAttribArray",
  "glDrawArrays",
  "glDrawElements",
  "glEnable",
  "glEnableClientState",
  "glEnableVertexAttribArray",
  "glEndQuery",
  "glFinish",
  "glFlush",
  "glFramebufferRenderbuffer",
  "glFramebufferTexture2D",
  "glFrontFace",
  "glGenBuffers",
  "glGenFramebuffers",
  "glGenQueries",
  "glGenRenderbuffers",
  "glGenTextures",
  "glGenerateMipmap",
  "glGetActiveAttrib",
  "glGetActiveUniform",
  "glGetAttachedShaders",
  "glGetAttribLocation",
  "glGetBooleanv",
  "glGetBufferParameteriv",
  "glGetError",
  "glGetFloatv",
  "glGetFramebufferAttachmentParameteriv",
  "glGetIntegerv",
  "glGetProgramInfoLog",
  "glGetProgramiv",
  "glGetQueryObjectuiv",
  "glGetShaderInfoLog",
  "glGetShaderSource",
  "glGetShaderiv",
  "glGetString",
  "glGetUniformLocation",
  "glGetVertexAttribPointerv",
  "glGetVertexAttribfv",
  "glGetVertexAttribiv",
  "glHint",
  "glIsEnabled",
  "glIsFramebuffer",
  "glIsProgram",
  "glIsRenderbuffer",
  "glIsTexture",
  "glLineWidth",
  "glLinkProgram",
  "glMapBuffer",
  "glPixelStorei",
  "glPolygonOffset",
  "glReadPixels",
  "glRenderbufferStorage",
  "glScissor",
  "glShaderBinary",
  "glShaderSource",
  "glStencilFunc",
  "glStencilFuncSeparate",
  "glStencilMask",
  "glStencilMaskSeparate",
  "glStencilOp",
  "glStencilOpSeparate",
  "glTexCoordPointer",
  "glTexImage2D",
  "glTexParameterf",
  "glTexParameteri",
  "glTexParameteriv",
  "glTexSubImage2D",
  "glUniform1f",
  "glUniform1fv",
  "glUniform1i",
  "glUniform1iv",
  "glUniform2f",
  "glUniform2fv",
  "glUniform2i",
  "glUniform2iv",
  "glUniform3f",
  "glUniform3fv",
  "glUniform3i",
  "glUniform3iv",
  "glUniform4f",
  "glUniform4fv",
  "glUniform4i",
  "glUniform4iv",
  "glUniformMatrix2fv",
  "glUniformMatrix3fv",
  "glUniformMatrix4fv",
  "glUnmapBuffer",
  "glUseProgram",
  "glVertexAttrib1f",
  "glVertexAttrib1fv",
  "glVertexAttrib2f",
  "glVertexAttrib2fv",
  "glVertexAttrib3f",
  "glVertexAttrib3fv",
  "glVertexAttrib4f",
  "glVertexAttrib4fv",
  "glVertexAttribPointer",
  "glVertexPointer",
  "glViewport",
  "vglGetProcAddress",
  "vglInit",
  "vglInitExtended",
  "vglSetupRuntimeShaderCompiler",
  "vglSwapBuffers",
};

extern void __real_glActiveTexture(GLenum texture);
extern void __real_glAttachShader(GLuint prog, GLuint shad);
extern void __real_glBeginQuery(GLenum target, GLuint id);
extern void __real_glBindAttribLocation(GLuint program, GLuint index, const GLchar* name);
extern void __real_glBindBuffer(GLenum target, GLuint buffer);
extern void __real_glBindFramebuffer(GLenum target, GLuint framebuffer);
extern void __real_glBindRenderbuffer(GLenum target, GLuint renderbuffer);
extern void __real_glBindTexture(GLenum target, GLuint texture);
extern void __real_glBlendEquation(GLenum mode);
extern void __real_glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha);
extern void __real_glBlendFunc(GLenum sfactor, GLenum dfactor);
extern void __real_glBlendFuncSeparate(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
extern void __real_glBufferData(GLenum target, GLsizei size, const GLvoid* data, GLenum usage);
extern void __real_glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void* data);
extern GLenum __real_glCheckFramebufferStatus(GLenum target);
extern void __real_glClear(GLbitfield mask);
extern void __real_glClearColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void __real_glClearDepthf(GLclampf depth);
extern void __real_glClearStencil(GLint s);
extern void __real_glColor4f(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
extern void __real_glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
extern void __real_glCompileShader(GLuint shader);
extern void __real_glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void* data);
extern void __real_glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
extern void __real_glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
extern GLuint __real_glCreateProgram(void);
extern GLuint __real_glCreateShader(GLenum shaderType);
extern void __real_glCullFace(GLenum mode);
extern void __real_glDeleteBuffers(GLsizei n, const GLuint* gl_buffers);
extern void __real_glDeleteFramebuffers(GLsizei n, const GLuint* framebuffers);
extern void __real_glDeleteProgram(GLuint prog);
extern void __real_glDeleteRenderbuffers(GLsizei n, const GLuint* renderbuffers);
extern void __real_glDeleteShader(GLuint shad);
extern void __real_glDeleteTextures(GLsizei n, const GLuint* textures);
extern void __real_glDepthFunc(GLenum func);
extern void __real_glDepthMask(GLboolean flag);
extern void __real_glDepthRangef(GLfloat nearVal, GLfloat farVal);
extern void __real_glDisable(GLenum cap);
extern void __real_glDisableClientState(GLenum array);
extern void __real_glDisableVertexAttribArray(GLuint index);
extern void __real_glDrawArrays(GLenum mode, GLint first, GLsizei count);
extern void __real_glDrawElements(GLenum mode, GLsizei count, GLenum type, const GLvoid* indices);
extern void __real_glEnable(GLenum cap);
extern void __real_glEnableClientState(GLenum array);
extern void __real_glEnableVertexAttribArray(GLuint index);
extern void __real_glEndQuery(GLenum target);
extern void __real_glFinish(void);
extern void __real_glFlush(void);
extern void __real_glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
extern void __real_glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
extern void __real_glFrontFace(GLenum mode);
extern void __real_glGenBuffers(GLsizei n, GLuint* buffers);
extern void __real_glGenFramebuffers(GLsizei n, GLuint* framebuffers);
extern void __real_glGenQueries(GLsizei n, GLuint* ids);
extern void __real_glGenRenderbuffers(GLsizei n, GLuint* renderbuffers);
extern void __real_glGenTextures(GLsizei n, GLuint* textures);
extern void __real_glGenerateMipmap(GLenum target);
extern void __real_glGetActiveAttrib(GLuint prog, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
extern void __real_glGetActiveUniform(GLuint prog, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name);
extern void __real_glGetAttachedShaders(GLuint prog, GLsizei maxCount, GLsizei* count, GLuint* shads);
extern GLint __real_glGetAttribLocation(GLuint prog, const GLchar* name);
extern void __real_glGetBooleanv(GLenum pname, GLboolean* params);
extern void __real_glGetBufferParameteriv(GLenum target, GLenum pname, GLint* params);
extern GLenum __real_glGetError(void);
extern void __real_glGetFloatv(GLenum pname, GLfloat* data);
extern void __real_glGetFramebufferAttachmentParameteriv(GLenum target, GLenum attachment, GLenum pname, GLint* params);
extern void __real_glGetIntegerv(GLenum pname, GLint* data);
extern void __real_glGetProgramInfoLog(GLuint program, GLsizei maxLength, GLsizei* length, GLchar* infoLog);
extern void __real_glGetProgramiv(GLuint program, GLenum pname, GLint* params);
extern void __real_glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint* params);
extern void __real_glGetShaderInfoLog(GLuint handle, GLsizei maxLength, GLsizei* length, GLchar* infoLog);
extern void __real_glGetShaderSource(GLuint handle, GLsizei bufSize, GLsizei* length, GLchar* source);
extern void __real_glGetShaderiv(GLuint handle, GLenum pname, GLint* params);
extern const GLubyte * __real_glGetString(GLenum name);
extern GLint __real_glGetUniformLocation(GLuint prog, const GLchar* name);
extern void __real_glGetVertexAttribPointerv(GLuint index, GLenum pname, void** pointer);
extern void __real_glGetVertexAttribfv(GLuint index, GLenum pname, GLfloat* params);
extern void __real_glGetVertexAttribiv(GLuint index, GLenum pname, GLint* params);
extern void __real_glHint(GLenum target, GLenum mode);
extern GLboolean __real_glIsEnabled(GLenum cap);
extern GLboolean __real_glIsFramebuffer(GLuint fb);
extern GLboolean __real_glIsProgram(GLuint program);
extern GLboolean __real_glIsRenderbuffer(GLuint rb);
extern GLboolean __real_glIsTexture(GLuint texture);
extern void __real_glLineWidth(GLfloat width);
extern void __real_glLinkProgram(GLuint progr);
extern void * __real_glMapBuffer(GLenum target, GLbitfield access);
extern void __real_glPixelStorei(GLenum pname, GLint param);
extern void __real_glPolygonOffset(GLfloat factor, GLfloat units);
extern void __real_glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* data);
extern void __real_glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
extern void __real_glScissor(GLint x, GLint y, GLsizei width, GLsizei height);
extern void __real_glShaderBinary(GLsizei count, const GLuint* handles, GLenum binaryFormat, const void* binary, GLsizei length);
extern void __real_glShaderSource(GLuint handle, GLsizei count, const GLchar*const* string, const GLint* length);
extern void __real_glStencilFunc(GLenum func, GLint ref, GLuint mask);
extern void __real_glStencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask);
extern void __real_glStencilMask(GLuint mask);
extern void __real_glStencilMaskSeparate(GLenum face, GLuint mask);
extern void __real_glStencilOp(GLenum sfail, GLenum dpfail, GLenum dppass);
extern void __real_glStencilOpSeparate(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
extern void __real_glTexCoordPointer(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer);
extern void __real_glTexImage2D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid* data);
extern void __real_glTexParameterf(GLenum target, GLenum pname, GLfloat param);
extern void __real_glTexParameteri(GLenum target, GLenum pname, GLint param);
extern void __real_glTexParameteriv(GLenum target, GLenum pname, GLint* param);
extern void __real_glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid* pixels);
extern void __real_glUniform1f(GLint location, GLfloat v0);
extern void __real_glUniform1fv(GLint location, GLsizei count, const GLfloat* value);
extern void __real_glUniform1i(GLint location, GLint v0);
extern void __real_glUniform1iv(GLint location, GLsizei count, const GLint* value);
extern void __real_glUniform2f(GLint location, GLfloat v0, GLfloat v1);
extern void __real_glUniform2fv(GLint location, GLsizei count, const GLfloat* value);
extern void __real_glUniform2i(GLint location, GLint v0, GLint v1);
extern void __real_glUniform2iv(GLint location, GLsizei count, const GLint* value);
extern void __real_glUniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
extern void __real_glUniform3fv(GLint location, GLsizei count, const GLfloat* value);
extern void __real_glUniform3i(GLint location, GLint v0, GLint v1, GLint v2);
extern void __real_glUniform3iv(GLint location, GLsizei count, const GLint* value);
extern void __real_glUniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
extern void __real_glUniform4fv(GLint location, GLsizei count, const GLfloat* value);
extern void __real_glUniform4i(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
extern void __real_glUniform4iv(GLint location, GLsizei count, const GLint* value);
extern void __real_glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void __real_glUniformMatrix3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern void __real_glUniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value);
extern GLboolean __real_glUnmapBuffer(GLenum target);
extern void __real_glUseProgram(GLuint program);
extern void __real_glVertexAttrib1f(GLuint index, GLfloat v0);
extern void __real_glVertexAttrib1fv(GLuint index, const GLfloat* v);
extern void __real_glVertexAttrib2f(GLuint index, GLfloat v0, GLfloat v1);
extern void __real_glVertexAttrib2fv(GLuint index, const GLfloat* v);
extern void __real_glVertexAttrib3f(GLuint index, GLfloat v0, GLfloat v1, GLfloat v2);
extern void __real_glVertexAttrib3fv(GLuint index, const GLfloat* v);
extern void __real_glVertexAttrib4f(GLuint index, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
extern void __real_glVertexAttrib4fv(GLuint index, const GLfloat* v);
extern void __real_glVertexAttribPointer(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void* pointer);
extern void __real_glVertexPointer(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer);
extern void __real_glViewport(GLint x, GLint y, GLsizei width, GLsizei height);
extern void * __real_vglGetProcAddress(const char* name);
extern GLboolean __real_vglInit(int legacy_pool_size);
extern GLboolean __real_vglInitExtended(int legacy_pool_size, int width, int height, int ram_threshold, SceGxmMultisampleMode msaa);
extern void __real_vglSetupRuntimeShaderCompiler(shark_opt opt_level, int32_t use_fastmath, int32_t use_fastprecision, int32_t use_fastint);
extern void __real_vglSwapBuffers(GLboolean has_commondialog);

void __wrap_glActiveTexture(GLenum texture) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glActiveTexture(texture); return; }
  uint32_t v[1] = {(uint32_t)texture};
  if (glw_dedup(16, GLW_OP_glActiveTexture, v, 1)) return;
  uint32_t *a = glw_begin(GLW_OP_glActiveTexture, 1, 0);
  a[0] = (uint32_t)texture;
  glw_end(a);
}

void __wrap_glAttachShader(GLuint prog, GLuint shad) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glAttachShader(prog, shad); return; }
  uint32_t *a = glw_begin(GLW_OP_glAttachShader, 2, 0);
  a[0] = (uint32_t)prog;
  a[1] = (uint32_t)shad;
  glw_end(a);
}

void __wrap_glBindAttribLocation(GLuint program, GLuint index, const GLchar* name) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glBindAttribLocation(program, index, name); return; }
  uint32_t bytes = name ? (uint32_t)(strlen(name) + 1) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glBindAttribLocation | GLW_SYNC, 3, 0);
    a[0] = (uint32_t)program;
    a[1] = (uint32_t)index;
    a[2] = (uint32_t)(uintptr_t)name;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glBindAttribLocation, 3, bytes);
  a[0] = (uint32_t)program;
  a[1] = (uint32_t)index;
  a[2] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 3, name, bytes);
  glw_end(a);
}

void __wrap_glBindRenderbuffer(GLenum target, GLuint renderbuffer) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glBindRenderbuffer(target, renderbuffer); return; }
  uint32_t *a = glw_begin(GLW_OP_glBindRenderbuffer, 2, 0);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)renderbuffer;
  glw_end(a);
}

void __wrap_glBindTexture(GLenum target, GLuint texture) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glBindTexture(target, texture); return; }
  uint32_t *a = glw_begin(GLW_OP_glBindTexture, 2, 0);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)texture;
  glw_end(a);
}

void __wrap_glBlendEquation(GLenum mode) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glBlendEquation(mode); return; }
  uint32_t v[1] = {(uint32_t)mode};
  if (glw_dedup(1, GLW_OP_glBlendEquation, v, 1)) return;
  uint32_t *a = glw_begin(GLW_OP_glBlendEquation, 1, 0);
  a[0] = (uint32_t)mode;
  glw_end(a);
}

void __wrap_glBlendEquationSeparate(GLenum modeRGB, GLenum modeAlpha) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glBlendEquationSeparate(modeRGB, modeAlpha); return; }
  uint32_t v[2] = {(uint32_t)modeRGB, (uint32_t)modeAlpha};
  if (glw_dedup(1, GLW_OP_glBlendEquationSeparate, v, 2)) return;
  uint32_t *a = glw_begin(GLW_OP_glBlendEquationSeparate, 2, 0);
  a[0] = (uint32_t)modeRGB;
  a[1] = (uint32_t)modeAlpha;
  glw_end(a);
}

void __wrap_glBlendFunc(GLenum sfactor, GLenum dfactor) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glBlendFunc(sfactor, dfactor); return; }
  uint32_t v[2] = {(uint32_t)sfactor, (uint32_t)dfactor};
  if (glw_dedup(0, GLW_OP_glBlendFunc, v, 2)) return;
  uint32_t *a = glw_begin(GLW_OP_glBlendFunc, 2, 0);
  a[0] = (uint32_t)sfactor;
  a[1] = (uint32_t)dfactor;
  glw_end(a);
}

void __wrap_glBlendFuncSeparate(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glBlendFuncSeparate(srcRGB, dstRGB, srcAlpha, dstAlpha); return; }
  uint32_t v[4] = {(uint32_t)srcRGB, (uint32_t)dstRGB, (uint32_t)srcAlpha, (uint32_t)dstAlpha};
  if (glw_dedup(0, GLW_OP_glBlendFuncSeparate, v, 4)) return;
  uint32_t *a = glw_begin(GLW_OP_glBlendFuncSeparate, 4, 0);
  a[0] = (uint32_t)srcRGB;
  a[1] = (uint32_t)dstRGB;
  a[2] = (uint32_t)srcAlpha;
  a[3] = (uint32_t)dstAlpha;
  glw_end(a);
}

void __wrap_glBufferData(GLenum target, GLsizei size, const GLvoid* data, GLenum usage) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glBufferData(target, size, data, usage); return; }
  uint32_t bytes = data ? (uint32_t)(size) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glBufferData | GLW_SYNC, 4, 0);
    a[0] = (uint32_t)target;
    a[1] = (uint32_t)size;
    a[2] = (uint32_t)(uintptr_t)data;
    a[3] = (uint32_t)usage;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glBufferData, 4, bytes);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)size;
  a[2] = bytes ? 1u : 0u;
  a[3] = (uint32_t)usage;
  if (bytes) memcpy(a + 4, data, bytes);
  glw_end(a);
}

void __wrap_glBufferSubData(GLenum target, GLintptr offset, GLsizeiptr size, const void* data) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glBufferSubData(target, offset, size, data); return; }
  uint32_t bytes = data ? (uint32_t)(size) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glBufferSubData | GLW_SYNC, 4, 0);
    a[0] = (uint32_t)target;
    a[1] = (uint32_t)offset;
    a[2] = (uint32_t)size;
    a[3] = (uint32_t)(uintptr_t)data;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glBufferSubData, 4, bytes);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)offset;
  a[2] = (uint32_t)size;
  a[3] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 4, data, bytes);
  glw_end(a);
}

GLenum __wrap_glCheckFramebufferStatus(GLenum target) {
  GLW_PROF(1);
  if (glw_direct()) return __real_glCheckFramebufferStatus(target);
  uint32_t *a = glw_begin(GLW_OP_glCheckFramebufferStatus | GLW_SYNC, 1, 0);
  a[0] = (uint32_t)target;
  return (GLenum)(uintptr_t)glw_sync(a);
}

void __wrap_glClear(GLbitfield mask) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glClear(mask); return; }
  uint32_t *a = glw_begin(GLW_OP_glClear, 1, 0);
  a[0] = (uint32_t)mask;
  glw_end(a);
}

void __wrap_glClearColor(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glClearColor(red, green, blue, alpha); return; }
  uint32_t v[4] = {glw_u(red), glw_u(green), glw_u(blue), glw_u(alpha)};
  if (glw_dedup(13, GLW_OP_glClearColor, v, 4)) return;
  uint32_t *a = glw_begin(GLW_OP_glClearColor, 4, 0);
  a[0] = glw_u(red);
  a[1] = glw_u(green);
  a[2] = glw_u(blue);
  a[3] = glw_u(alpha);
  glw_end(a);
}

void __wrap_glClearDepthf(GLclampf depth) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glClearDepthf(depth); return; }
  uint32_t v[1] = {glw_u(depth)};
  if (glw_dedup(14, GLW_OP_glClearDepthf, v, 1)) return;
  uint32_t *a = glw_begin(GLW_OP_glClearDepthf, 1, 0);
  a[0] = glw_u(depth);
  glw_end(a);
}

void __wrap_glClearStencil(GLint s) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glClearStencil(s); return; }
  uint32_t v[1] = {(uint32_t)s};
  if (glw_dedup(15, GLW_OP_glClearStencil, v, 1)) return;
  uint32_t *a = glw_begin(GLW_OP_glClearStencil, 1, 0);
  a[0] = (uint32_t)s;
  glw_end(a);
}

void __wrap_glColor4f(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glColor4f(red, green, blue, alpha); return; }
  uint32_t *a = glw_begin(GLW_OP_glColor4f, 4, 0);
  a[0] = glw_u(red);
  a[1] = glw_u(green);
  a[2] = glw_u(blue);
  a[3] = glw_u(alpha);
  glw_end(a);
}

void __wrap_glColorMask(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glColorMask(red, green, blue, alpha); return; }
  uint32_t v[4] = {(uint32_t)red, (uint32_t)green, (uint32_t)blue, (uint32_t)alpha};
  if (glw_dedup(7, GLW_OP_glColorMask, v, 4)) return;
  uint32_t *a = glw_begin(GLW_OP_glColorMask, 4, 0);
  a[0] = (uint32_t)red;
  a[1] = (uint32_t)green;
  a[2] = (uint32_t)blue;
  a[3] = (uint32_t)alpha;
  glw_end(a);
}

void __wrap_glCompileShader(GLuint shader) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glCompileShader(shader); return; }
  uint32_t *a = glw_begin(GLW_OP_glCompileShader, 1, 0);
  a[0] = (uint32_t)shader;
  glw_end(a);
}

void __wrap_glCompressedTexImage2D(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void* data) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glCompressedTexImage2D(target, level, internalformat, width, height, border, imageSize, data); return; }
  uint32_t bytes = data ? (uint32_t)(imageSize) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glCompressedTexImage2D | GLW_SYNC, 8, 0);
    a[0] = (uint32_t)target;
    a[1] = (uint32_t)level;
    a[2] = (uint32_t)internalformat;
    a[3] = (uint32_t)width;
    a[4] = (uint32_t)height;
    a[5] = (uint32_t)border;
    a[6] = (uint32_t)imageSize;
    a[7] = (uint32_t)(uintptr_t)data;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glCompressedTexImage2D, 8, bytes);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)level;
  a[2] = (uint32_t)internalformat;
  a[3] = (uint32_t)width;
  a[4] = (uint32_t)height;
  a[5] = (uint32_t)border;
  a[6] = (uint32_t)imageSize;
  a[7] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 8, data, bytes);
  glw_end(a);
}

void __wrap_glCopyTexImage2D(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glCopyTexImage2D(target, level, internalformat, x, y, width, height, border); return; }
  uint32_t *a = glw_begin(GLW_OP_glCopyTexImage2D, 8, 0);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)level;
  a[2] = (uint32_t)internalformat;
  a[3] = (uint32_t)x;
  a[4] = (uint32_t)y;
  a[5] = (uint32_t)width;
  a[6] = (uint32_t)height;
  a[7] = (uint32_t)border;
  glw_end(a);
}

void __wrap_glCopyTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glCopyTexSubImage2D(target, level, xoffset, yoffset, x, y, width, height); return; }
  uint32_t *a = glw_begin(GLW_OP_glCopyTexSubImage2D, 8, 0);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)level;
  a[2] = (uint32_t)xoffset;
  a[3] = (uint32_t)yoffset;
  a[4] = (uint32_t)x;
  a[5] = (uint32_t)y;
  a[6] = (uint32_t)width;
  a[7] = (uint32_t)height;
  glw_end(a);
}

GLuint __wrap_glCreateShader(GLenum shaderType) {
  GLW_PROF(1);
  if (glw_direct()) return __real_glCreateShader(shaderType);
  uint32_t *a = glw_begin(GLW_OP_glCreateShader | GLW_SYNC, 1, 0);
  a[0] = (uint32_t)shaderType;
  return (GLuint)(uintptr_t)glw_sync(a);
}

void __wrap_glCullFace(GLenum mode) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glCullFace(mode); return; }
  uint32_t v[1] = {(uint32_t)mode};
  if (glw_dedup(5, GLW_OP_glCullFace, v, 1)) return;
  uint32_t *a = glw_begin(GLW_OP_glCullFace, 1, 0);
  a[0] = (uint32_t)mode;
  glw_end(a);
}

void __wrap_glDeleteFramebuffers(GLsizei n, const GLuint* framebuffers) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glDeleteFramebuffers(n, framebuffers); return; }
  uint32_t bytes = framebuffers ? (uint32_t)(n * 4) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glDeleteFramebuffers | GLW_SYNC, 2, 0);
    a[0] = (uint32_t)n;
    a[1] = (uint32_t)(uintptr_t)framebuffers;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glDeleteFramebuffers, 2, bytes);
  a[0] = (uint32_t)n;
  a[1] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 2, framebuffers, bytes);
  glw_end(a);
}

void __wrap_glDeleteRenderbuffers(GLsizei n, const GLuint* renderbuffers) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glDeleteRenderbuffers(n, renderbuffers); return; }
  uint32_t bytes = renderbuffers ? (uint32_t)(n * 4) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glDeleteRenderbuffers | GLW_SYNC, 2, 0);
    a[0] = (uint32_t)n;
    a[1] = (uint32_t)(uintptr_t)renderbuffers;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glDeleteRenderbuffers, 2, bytes);
  a[0] = (uint32_t)n;
  a[1] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 2, renderbuffers, bytes);
  glw_end(a);
}

void __wrap_glDeleteShader(GLuint shad) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glDeleteShader(shad); return; }
  uint32_t *a = glw_begin(GLW_OP_glDeleteShader, 1, 0);
  a[0] = (uint32_t)shad;
  glw_end(a);
}

void __wrap_glDeleteTextures(GLsizei n, const GLuint* textures) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glDeleteTextures(n, textures); return; }
  uint32_t bytes = textures ? (uint32_t)(n * 4) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glDeleteTextures | GLW_SYNC, 2, 0);
    a[0] = (uint32_t)n;
    a[1] = (uint32_t)(uintptr_t)textures;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glDeleteTextures, 2, bytes);
  a[0] = (uint32_t)n;
  a[1] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 2, textures, bytes);
  glw_end(a);
}

void __wrap_glDepthFunc(GLenum func) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glDepthFunc(func); return; }
  uint32_t v[1] = {(uint32_t)func};
  if (glw_dedup(2, GLW_OP_glDepthFunc, v, 1)) return;
  uint32_t *a = glw_begin(GLW_OP_glDepthFunc, 1, 0);
  a[0] = (uint32_t)func;
  glw_end(a);
}

void __wrap_glDepthMask(GLboolean flag) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glDepthMask(flag); return; }
  uint32_t v[1] = {(uint32_t)flag};
  if (glw_dedup(3, GLW_OP_glDepthMask, v, 1)) return;
  uint32_t *a = glw_begin(GLW_OP_glDepthMask, 1, 0);
  a[0] = (uint32_t)flag;
  glw_end(a);
}

void __wrap_glDepthRangef(GLfloat nearVal, GLfloat farVal) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glDepthRangef(nearVal, farVal); return; }
  uint32_t v[2] = {glw_u(nearVal), glw_u(farVal)};
  if (glw_dedup(4, GLW_OP_glDepthRangef, v, 2)) return;
  uint32_t *a = glw_begin(GLW_OP_glDepthRangef, 2, 0);
  a[0] = glw_u(nearVal);
  a[1] = glw_u(farVal);
  glw_end(a);
}

void __wrap_glFinish(void) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glFinish(); return; }
  uint32_t *a = glw_begin(GLW_OP_glFinish | GLW_SYNC, 0, 0);
  (void)glw_sync(a);
}

void __wrap_glFlush(void) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glFlush(); return; }
  uint32_t *a = glw_begin(GLW_OP_glFlush, 0, 0);
  glw_end(a);
}

void __wrap_glFramebufferRenderbuffer(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glFramebufferRenderbuffer(target, attachment, renderbuffertarget, renderbuffer); return; }
  uint32_t *a = glw_begin(GLW_OP_glFramebufferRenderbuffer, 4, 0);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)attachment;
  a[2] = (uint32_t)renderbuffertarget;
  a[3] = (uint32_t)renderbuffer;
  glw_end(a);
}

void __wrap_glFramebufferTexture2D(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glFramebufferTexture2D(target, attachment, textarget, texture, level); return; }
  uint32_t *a = glw_begin(GLW_OP_glFramebufferTexture2D, 5, 0);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)attachment;
  a[2] = (uint32_t)textarget;
  a[3] = (uint32_t)texture;
  a[4] = (uint32_t)level;
  glw_end(a);
}

void __wrap_glFrontFace(GLenum mode) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glFrontFace(mode); return; }
  uint32_t v[1] = {(uint32_t)mode};
  if (glw_dedup(6, GLW_OP_glFrontFace, v, 1)) return;
  uint32_t *a = glw_begin(GLW_OP_glFrontFace, 1, 0);
  a[0] = (uint32_t)mode;
  glw_end(a);
}

void __wrap_glGenBuffers(GLsizei n, GLuint* buffers) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGenBuffers(n, buffers); return; }
  uint32_t *a = glw_begin(GLW_OP_glGenBuffers | GLW_SYNC, 2, 0);
  a[0] = (uint32_t)n;
  a[1] = (uint32_t)(uintptr_t)buffers;
  (void)glw_sync(a);
}

void __wrap_glGenFramebuffers(GLsizei n, GLuint* framebuffers) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGenFramebuffers(n, framebuffers); return; }
  uint32_t *a = glw_begin(GLW_OP_glGenFramebuffers | GLW_SYNC, 2, 0);
  a[0] = (uint32_t)n;
  a[1] = (uint32_t)(uintptr_t)framebuffers;
  (void)glw_sync(a);
}

void __wrap_glGenRenderbuffers(GLsizei n, GLuint* renderbuffers) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGenRenderbuffers(n, renderbuffers); return; }
  uint32_t *a = glw_begin(GLW_OP_glGenRenderbuffers | GLW_SYNC, 2, 0);
  a[0] = (uint32_t)n;
  a[1] = (uint32_t)(uintptr_t)renderbuffers;
  (void)glw_sync(a);
}

void __wrap_glGenTextures(GLsizei n, GLuint* textures) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGenTextures(n, textures); return; }
  uint32_t *a = glw_begin(GLW_OP_glGenTextures | GLW_SYNC, 2, 0);
  a[0] = (uint32_t)n;
  a[1] = (uint32_t)(uintptr_t)textures;
  (void)glw_sync(a);
}

void __wrap_glGenerateMipmap(GLenum target) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGenerateMipmap(target); return; }
  uint32_t *a = glw_begin(GLW_OP_glGenerateMipmap, 1, 0);
  a[0] = (uint32_t)target;
  glw_end(a);
}

void __wrap_glGetActiveAttrib(GLuint prog, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetActiveAttrib(prog, index, bufSize, length, size, type, name); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetActiveAttrib | GLW_SYNC, 7, 0);
  a[0] = (uint32_t)prog;
  a[1] = (uint32_t)index;
  a[2] = (uint32_t)bufSize;
  a[3] = (uint32_t)(uintptr_t)length;
  a[4] = (uint32_t)(uintptr_t)size;
  a[5] = (uint32_t)(uintptr_t)type;
  a[6] = (uint32_t)(uintptr_t)name;
  (void)glw_sync(a);
}

void __wrap_glGetActiveUniform(GLuint prog, GLuint index, GLsizei bufSize, GLsizei* length, GLint* size, GLenum* type, GLchar* name) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetActiveUniform(prog, index, bufSize, length, size, type, name); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetActiveUniform | GLW_SYNC, 7, 0);
  a[0] = (uint32_t)prog;
  a[1] = (uint32_t)index;
  a[2] = (uint32_t)bufSize;
  a[3] = (uint32_t)(uintptr_t)length;
  a[4] = (uint32_t)(uintptr_t)size;
  a[5] = (uint32_t)(uintptr_t)type;
  a[6] = (uint32_t)(uintptr_t)name;
  (void)glw_sync(a);
}

void __wrap_glGetAttachedShaders(GLuint prog, GLsizei maxCount, GLsizei* count, GLuint* shads) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetAttachedShaders(prog, maxCount, count, shads); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetAttachedShaders | GLW_SYNC, 4, 0);
  a[0] = (uint32_t)prog;
  a[1] = (uint32_t)maxCount;
  a[2] = (uint32_t)(uintptr_t)count;
  a[3] = (uint32_t)(uintptr_t)shads;
  (void)glw_sync(a);
}

GLint __wrap_glGetAttribLocation(GLuint prog, const GLchar* name) {
  GLW_PROF(1);
  if (glw_direct()) return __real_glGetAttribLocation(prog, name);
  uint32_t *a = glw_begin(GLW_OP_glGetAttribLocation | GLW_SYNC, 2, 0);
  a[0] = (uint32_t)prog;
  a[1] = (uint32_t)(uintptr_t)name;
  return (GLint)(uintptr_t)glw_sync(a);
}

void __wrap_glGetBooleanv(GLenum pname, GLboolean* params) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetBooleanv(pname, params); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetBooleanv | GLW_SYNC, 2, 0);
  a[0] = (uint32_t)pname;
  a[1] = (uint32_t)(uintptr_t)params;
  (void)glw_sync(a);
}

void __wrap_glGetBufferParameteriv(GLenum target, GLenum pname, GLint* params) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetBufferParameteriv(target, pname, params); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetBufferParameteriv | GLW_SYNC, 3, 0);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)pname;
  a[2] = (uint32_t)(uintptr_t)params;
  (void)glw_sync(a);
}

void __wrap_glGetFloatv(GLenum pname, GLfloat* data) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetFloatv(pname, data); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetFloatv | GLW_SYNC, 2, 0);
  a[0] = (uint32_t)pname;
  a[1] = (uint32_t)(uintptr_t)data;
  (void)glw_sync(a);
}

void __wrap_glGetFramebufferAttachmentParameteriv(GLenum target, GLenum attachment, GLenum pname, GLint* params) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetFramebufferAttachmentParameteriv(target, attachment, pname, params); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetFramebufferAttachmentParameteriv | GLW_SYNC, 4, 0);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)attachment;
  a[2] = (uint32_t)pname;
  a[3] = (uint32_t)(uintptr_t)params;
  (void)glw_sync(a);
}

void __wrap_glGetProgramInfoLog(GLuint program, GLsizei maxLength, GLsizei* length, GLchar* infoLog) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetProgramInfoLog(program, maxLength, length, infoLog); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetProgramInfoLog | GLW_SYNC, 4, 0);
  a[0] = (uint32_t)program;
  a[1] = (uint32_t)maxLength;
  a[2] = (uint32_t)(uintptr_t)length;
  a[3] = (uint32_t)(uintptr_t)infoLog;
  (void)glw_sync(a);
}

void __wrap_glGetProgramiv(GLuint program, GLenum pname, GLint* params) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetProgramiv(program, pname, params); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetProgramiv | GLW_SYNC, 3, 0);
  a[0] = (uint32_t)program;
  a[1] = (uint32_t)pname;
  a[2] = (uint32_t)(uintptr_t)params;
  (void)glw_sync(a);
}

void __wrap_glGetShaderInfoLog(GLuint handle, GLsizei maxLength, GLsizei* length, GLchar* infoLog) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetShaderInfoLog(handle, maxLength, length, infoLog); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetShaderInfoLog | GLW_SYNC, 4, 0);
  a[0] = (uint32_t)handle;
  a[1] = (uint32_t)maxLength;
  a[2] = (uint32_t)(uintptr_t)length;
  a[3] = (uint32_t)(uintptr_t)infoLog;
  (void)glw_sync(a);
}

void __wrap_glGetShaderSource(GLuint handle, GLsizei bufSize, GLsizei* length, GLchar* source) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetShaderSource(handle, bufSize, length, source); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetShaderSource | GLW_SYNC, 4, 0);
  a[0] = (uint32_t)handle;
  a[1] = (uint32_t)bufSize;
  a[2] = (uint32_t)(uintptr_t)length;
  a[3] = (uint32_t)(uintptr_t)source;
  (void)glw_sync(a);
}

void __wrap_glGetShaderiv(GLuint handle, GLenum pname, GLint* params) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetShaderiv(handle, pname, params); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetShaderiv | GLW_SYNC, 3, 0);
  a[0] = (uint32_t)handle;
  a[1] = (uint32_t)pname;
  a[2] = (uint32_t)(uintptr_t)params;
  (void)glw_sync(a);
}

const GLubyte * __wrap_glGetString(GLenum name) {
  GLW_PROF(1);
  if (glw_direct()) return __real_glGetString(name);
  uint32_t *a = glw_begin(GLW_OP_glGetString | GLW_SYNC, 1, 0);
  a[0] = (uint32_t)name;
  return (const GLubyte *)(uintptr_t)glw_sync(a);
}

GLint __wrap_glGetUniformLocation(GLuint prog, const GLchar* name) {
  GLW_PROF(1);
  if (glw_direct()) return __real_glGetUniformLocation(prog, name);
  uint32_t *a = glw_begin(GLW_OP_glGetUniformLocation | GLW_SYNC, 2, 0);
  a[0] = (uint32_t)prog;
  a[1] = (uint32_t)(uintptr_t)name;
  return (GLint)(uintptr_t)glw_sync(a);
}

void __wrap_glGetVertexAttribPointerv(GLuint index, GLenum pname, void** pointer) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetVertexAttribPointerv(index, pname, pointer); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetVertexAttribPointerv | GLW_SYNC, 3, 0);
  a[0] = (uint32_t)index;
  a[1] = (uint32_t)pname;
  a[2] = (uint32_t)(uintptr_t)pointer;
  (void)glw_sync(a);
}

void __wrap_glGetVertexAttribfv(GLuint index, GLenum pname, GLfloat* params) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetVertexAttribfv(index, pname, params); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetVertexAttribfv | GLW_SYNC, 3, 0);
  a[0] = (uint32_t)index;
  a[1] = (uint32_t)pname;
  a[2] = (uint32_t)(uintptr_t)params;
  (void)glw_sync(a);
}

void __wrap_glGetVertexAttribiv(GLuint index, GLenum pname, GLint* params) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glGetVertexAttribiv(index, pname, params); return; }
  uint32_t *a = glw_begin(GLW_OP_glGetVertexAttribiv | GLW_SYNC, 3, 0);
  a[0] = (uint32_t)index;
  a[1] = (uint32_t)pname;
  a[2] = (uint32_t)(uintptr_t)params;
  (void)glw_sync(a);
}

void __wrap_glHint(GLenum target, GLenum mode) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glHint(target, mode); return; }
  uint32_t *a = glw_begin(GLW_OP_glHint, 2, 0);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)mode;
  glw_end(a);
}

GLboolean __wrap_glIsFramebuffer(GLuint fb) {
  GLW_PROF(1);
  if (glw_direct()) return __real_glIsFramebuffer(fb);
  uint32_t *a = glw_begin(GLW_OP_glIsFramebuffer | GLW_SYNC, 1, 0);
  a[0] = (uint32_t)fb;
  return (GLboolean)(uintptr_t)glw_sync(a);
}

GLboolean __wrap_glIsRenderbuffer(GLuint rb) {
  GLW_PROF(1);
  if (glw_direct()) return __real_glIsRenderbuffer(rb);
  uint32_t *a = glw_begin(GLW_OP_glIsRenderbuffer | GLW_SYNC, 1, 0);
  a[0] = (uint32_t)rb;
  return (GLboolean)(uintptr_t)glw_sync(a);
}

GLboolean __wrap_glIsTexture(GLuint texture) {
  GLW_PROF(1);
  if (glw_direct()) return __real_glIsTexture(texture);
  uint32_t *a = glw_begin(GLW_OP_glIsTexture | GLW_SYNC, 1, 0);
  a[0] = (uint32_t)texture;
  return (GLboolean)(uintptr_t)glw_sync(a);
}

void __wrap_glLineWidth(GLfloat width) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glLineWidth(width); return; }
  uint32_t v[1] = {glw_u(width)};
  if (glw_dedup(12, GLW_OP_glLineWidth, v, 1)) return;
  uint32_t *a = glw_begin(GLW_OP_glLineWidth, 1, 0);
  a[0] = glw_u(width);
  glw_end(a);
}

void __wrap_glLinkProgram(GLuint progr) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glLinkProgram(progr); return; }
  uint32_t *a = glw_begin(GLW_OP_glLinkProgram, 1, 0);
  a[0] = (uint32_t)progr;
  glw_end(a);
}

void * __wrap_glMapBuffer(GLenum target, GLbitfield access) {
  GLW_PROF(1);
  if (glw_direct()) return __real_glMapBuffer(target, access);
  uint32_t *a = glw_begin(GLW_OP_glMapBuffer | GLW_SYNC, 2, 0);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)access;
  return (void *)(uintptr_t)glw_sync(a);
}

void __wrap_glPolygonOffset(GLfloat factor, GLfloat units) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glPolygonOffset(factor, units); return; }
  uint32_t v[2] = {glw_u(factor), glw_u(units)};
  if (glw_dedup(11, GLW_OP_glPolygonOffset, v, 2)) return;
  uint32_t *a = glw_begin(GLW_OP_glPolygonOffset, 2, 0);
  a[0] = glw_u(factor);
  a[1] = glw_u(units);
  glw_end(a);
}

void __wrap_glReadPixels(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid* data) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glReadPixels(x, y, width, height, format, type, data); return; }
  uint32_t *a = glw_begin(GLW_OP_glReadPixels | GLW_SYNC, 7, 0);
  a[0] = (uint32_t)x;
  a[1] = (uint32_t)y;
  a[2] = (uint32_t)width;
  a[3] = (uint32_t)height;
  a[4] = (uint32_t)format;
  a[5] = (uint32_t)type;
  a[6] = (uint32_t)(uintptr_t)data;
  (void)glw_sync(a);
}

void __wrap_glRenderbufferStorage(GLenum target, GLenum internalformat, GLsizei width, GLsizei height) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glRenderbufferStorage(target, internalformat, width, height); return; }
  uint32_t *a = glw_begin(GLW_OP_glRenderbufferStorage, 4, 0);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)internalformat;
  a[2] = (uint32_t)width;
  a[3] = (uint32_t)height;
  glw_end(a);
}

void __wrap_glShaderBinary(GLsizei count, const GLuint* handles, GLenum binaryFormat, const void* binary, GLsizei length) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glShaderBinary(count, handles, binaryFormat, binary, length); return; }
  uint32_t *a = glw_begin(GLW_OP_glShaderBinary | GLW_SYNC, 5, 0);
  a[0] = (uint32_t)count;
  a[1] = (uint32_t)(uintptr_t)handles;
  a[2] = (uint32_t)binaryFormat;
  a[3] = (uint32_t)(uintptr_t)binary;
  a[4] = (uint32_t)length;
  (void)glw_sync(a);
}

void __wrap_glShaderSource(GLuint handle, GLsizei count, const GLchar*const* string, const GLint* length) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glShaderSource(handle, count, string, length); return; }
  uint32_t *a = glw_begin(GLW_OP_glShaderSource | GLW_SYNC, 4, 0);
  a[0] = (uint32_t)handle;
  a[1] = (uint32_t)count;
  a[2] = (uint32_t)(uintptr_t)string;
  a[3] = (uint32_t)(uintptr_t)length;
  (void)glw_sync(a);
}

void __wrap_glStencilFunc(GLenum func, GLint ref, GLuint mask) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glStencilFunc(func, ref, mask); return; }
  uint32_t v[3] = {(uint32_t)func, (uint32_t)ref, (uint32_t)mask};
  if (glw_dedup(8, GLW_OP_glStencilFunc, v, 3)) return;
  uint32_t *a = glw_begin(GLW_OP_glStencilFunc, 3, 0);
  a[0] = (uint32_t)func;
  a[1] = (uint32_t)ref;
  a[2] = (uint32_t)mask;
  glw_end(a);
}

void __wrap_glStencilFuncSeparate(GLenum face, GLenum func, GLint ref, GLuint mask) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glStencilFuncSeparate(face, func, ref, mask); return; }
  uint32_t v[4] = {(uint32_t)face, (uint32_t)func, (uint32_t)ref, (uint32_t)mask};
  if (glw_dedup(8, GLW_OP_glStencilFuncSeparate, v, 4)) return;
  uint32_t *a = glw_begin(GLW_OP_glStencilFuncSeparate, 4, 0);
  a[0] = (uint32_t)face;
  a[1] = (uint32_t)func;
  a[2] = (uint32_t)ref;
  a[3] = (uint32_t)mask;
  glw_end(a);
}

void __wrap_glStencilMask(GLuint mask) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glStencilMask(mask); return; }
  uint32_t v[1] = {(uint32_t)mask};
  if (glw_dedup(10, GLW_OP_glStencilMask, v, 1)) return;
  uint32_t *a = glw_begin(GLW_OP_glStencilMask, 1, 0);
  a[0] = (uint32_t)mask;
  glw_end(a);
}

void __wrap_glStencilMaskSeparate(GLenum face, GLuint mask) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glStencilMaskSeparate(face, mask); return; }
  uint32_t v[2] = {(uint32_t)face, (uint32_t)mask};
  if (glw_dedup(10, GLW_OP_glStencilMaskSeparate, v, 2)) return;
  uint32_t *a = glw_begin(GLW_OP_glStencilMaskSeparate, 2, 0);
  a[0] = (uint32_t)face;
  a[1] = (uint32_t)mask;
  glw_end(a);
}

void __wrap_glStencilOp(GLenum sfail, GLenum dpfail, GLenum dppass) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glStencilOp(sfail, dpfail, dppass); return; }
  uint32_t v[3] = {(uint32_t)sfail, (uint32_t)dpfail, (uint32_t)dppass};
  if (glw_dedup(9, GLW_OP_glStencilOp, v, 3)) return;
  uint32_t *a = glw_begin(GLW_OP_glStencilOp, 3, 0);
  a[0] = (uint32_t)sfail;
  a[1] = (uint32_t)dpfail;
  a[2] = (uint32_t)dppass;
  glw_end(a);
}

void __wrap_glStencilOpSeparate(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glStencilOpSeparate(face, sfail, dpfail, dppass); return; }
  uint32_t v[4] = {(uint32_t)face, (uint32_t)sfail, (uint32_t)dpfail, (uint32_t)dppass};
  if (glw_dedup(9, GLW_OP_glStencilOpSeparate, v, 4)) return;
  uint32_t *a = glw_begin(GLW_OP_glStencilOpSeparate, 4, 0);
  a[0] = (uint32_t)face;
  a[1] = (uint32_t)sfail;
  a[2] = (uint32_t)dpfail;
  a[3] = (uint32_t)dppass;
  glw_end(a);
}

void __wrap_glTexImage2D(GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid* data) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glTexImage2D(target, level, internalFormat, width, height, border, format, type, data); return; }
  uint32_t bytes = data ? (uint32_t)(glw_pixels_size(width, height, format, type)) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glTexImage2D | GLW_SYNC, 9, 0);
    a[0] = (uint32_t)target;
    a[1] = (uint32_t)level;
    a[2] = (uint32_t)internalFormat;
    a[3] = (uint32_t)width;
    a[4] = (uint32_t)height;
    a[5] = (uint32_t)border;
    a[6] = (uint32_t)format;
    a[7] = (uint32_t)type;
    a[8] = (uint32_t)(uintptr_t)data;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glTexImage2D, 9, bytes);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)level;
  a[2] = (uint32_t)internalFormat;
  a[3] = (uint32_t)width;
  a[4] = (uint32_t)height;
  a[5] = (uint32_t)border;
  a[6] = (uint32_t)format;
  a[7] = (uint32_t)type;
  a[8] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 9, data, bytes);
  glw_end(a);
}

void __wrap_glTexParameterf(GLenum target, GLenum pname, GLfloat param) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glTexParameterf(target, pname, param); return; }
  uint32_t *a = glw_begin(GLW_OP_glTexParameterf, 3, 0);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)pname;
  a[2] = glw_u(param);
  glw_end(a);
}

void __wrap_glTexParameteri(GLenum target, GLenum pname, GLint param) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glTexParameteri(target, pname, param); return; }
  uint32_t *a = glw_begin(GLW_OP_glTexParameteri, 3, 0);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)pname;
  a[2] = (uint32_t)param;
  glw_end(a);
}

void __wrap_glTexParameteriv(GLenum target, GLenum pname, GLint* param) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glTexParameteriv(target, pname, param); return; }
  uint32_t bytes = param ? (uint32_t)(16) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glTexParameteriv | GLW_SYNC, 3, 0);
    a[0] = (uint32_t)target;
    a[1] = (uint32_t)pname;
    a[2] = (uint32_t)(uintptr_t)param;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glTexParameteriv, 3, bytes);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)pname;
  a[2] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 3, param, bytes);
  glw_end(a);
}

void __wrap_glTexSubImage2D(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid* pixels) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glTexSubImage2D(target, level, xoffset, yoffset, width, height, format, type, pixels); return; }
  uint32_t bytes = pixels ? (uint32_t)(glw_pixels_size(width, height, format, type)) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glTexSubImage2D | GLW_SYNC, 9, 0);
    a[0] = (uint32_t)target;
    a[1] = (uint32_t)level;
    a[2] = (uint32_t)xoffset;
    a[3] = (uint32_t)yoffset;
    a[4] = (uint32_t)width;
    a[5] = (uint32_t)height;
    a[6] = (uint32_t)format;
    a[7] = (uint32_t)type;
    a[8] = (uint32_t)(uintptr_t)pixels;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glTexSubImage2D, 9, bytes);
  a[0] = (uint32_t)target;
  a[1] = (uint32_t)level;
  a[2] = (uint32_t)xoffset;
  a[3] = (uint32_t)yoffset;
  a[4] = (uint32_t)width;
  a[5] = (uint32_t)height;
  a[6] = (uint32_t)format;
  a[7] = (uint32_t)type;
  a[8] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 9, pixels, bytes);
  glw_end(a);
}

void __wrap_glUniform1f(GLint location, GLfloat v0) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform1f(location, v0); return; }
  uint32_t *a = glw_begin(GLW_OP_glUniform1f, 2, 0);
  a[0] = (uint32_t)location;
  a[1] = glw_u(v0);
  glw_end(a);
}

void __wrap_glUniform1fv(GLint location, GLsizei count, const GLfloat* value) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform1fv(location, count, value); return; }
  uint32_t bytes = value ? (uint32_t)(count * 4) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glUniform1fv | GLW_SYNC, 3, 0);
    a[0] = (uint32_t)location;
    a[1] = (uint32_t)count;
    a[2] = (uint32_t)(uintptr_t)value;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glUniform1fv, 3, bytes);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)count;
  a[2] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 3, value, bytes);
  glw_end(a);
}

void __wrap_glUniform1i(GLint location, GLint v0) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform1i(location, v0); return; }
  uint32_t *a = glw_begin(GLW_OP_glUniform1i, 2, 0);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)v0;
  glw_end(a);
}

void __wrap_glUniform1iv(GLint location, GLsizei count, const GLint* value) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform1iv(location, count, value); return; }
  uint32_t bytes = value ? (uint32_t)(count * 4) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glUniform1iv | GLW_SYNC, 3, 0);
    a[0] = (uint32_t)location;
    a[1] = (uint32_t)count;
    a[2] = (uint32_t)(uintptr_t)value;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glUniform1iv, 3, bytes);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)count;
  a[2] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 3, value, bytes);
  glw_end(a);
}

void __wrap_glUniform2f(GLint location, GLfloat v0, GLfloat v1) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform2f(location, v0, v1); return; }
  uint32_t *a = glw_begin(GLW_OP_glUniform2f, 3, 0);
  a[0] = (uint32_t)location;
  a[1] = glw_u(v0);
  a[2] = glw_u(v1);
  glw_end(a);
}

void __wrap_glUniform2fv(GLint location, GLsizei count, const GLfloat* value) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform2fv(location, count, value); return; }
  uint32_t bytes = value ? (uint32_t)(count * 8) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glUniform2fv | GLW_SYNC, 3, 0);
    a[0] = (uint32_t)location;
    a[1] = (uint32_t)count;
    a[2] = (uint32_t)(uintptr_t)value;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glUniform2fv, 3, bytes);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)count;
  a[2] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 3, value, bytes);
  glw_end(a);
}

void __wrap_glUniform2i(GLint location, GLint v0, GLint v1) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform2i(location, v0, v1); return; }
  uint32_t *a = glw_begin(GLW_OP_glUniform2i, 3, 0);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)v0;
  a[2] = (uint32_t)v1;
  glw_end(a);
}

void __wrap_glUniform2iv(GLint location, GLsizei count, const GLint* value) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform2iv(location, count, value); return; }
  uint32_t bytes = value ? (uint32_t)(count * 8) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glUniform2iv | GLW_SYNC, 3, 0);
    a[0] = (uint32_t)location;
    a[1] = (uint32_t)count;
    a[2] = (uint32_t)(uintptr_t)value;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glUniform2iv, 3, bytes);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)count;
  a[2] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 3, value, bytes);
  glw_end(a);
}

void __wrap_glUniform3f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform3f(location, v0, v1, v2); return; }
  uint32_t *a = glw_begin(GLW_OP_glUniform3f, 4, 0);
  a[0] = (uint32_t)location;
  a[1] = glw_u(v0);
  a[2] = glw_u(v1);
  a[3] = glw_u(v2);
  glw_end(a);
}

void __wrap_glUniform3fv(GLint location, GLsizei count, const GLfloat* value) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform3fv(location, count, value); return; }
  uint32_t bytes = value ? (uint32_t)(count * 12) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glUniform3fv | GLW_SYNC, 3, 0);
    a[0] = (uint32_t)location;
    a[1] = (uint32_t)count;
    a[2] = (uint32_t)(uintptr_t)value;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glUniform3fv, 3, bytes);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)count;
  a[2] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 3, value, bytes);
  glw_end(a);
}

void __wrap_glUniform3i(GLint location, GLint v0, GLint v1, GLint v2) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform3i(location, v0, v1, v2); return; }
  uint32_t *a = glw_begin(GLW_OP_glUniform3i, 4, 0);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)v0;
  a[2] = (uint32_t)v1;
  a[3] = (uint32_t)v2;
  glw_end(a);
}

void __wrap_glUniform3iv(GLint location, GLsizei count, const GLint* value) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform3iv(location, count, value); return; }
  uint32_t bytes = value ? (uint32_t)(count * 12) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glUniform3iv | GLW_SYNC, 3, 0);
    a[0] = (uint32_t)location;
    a[1] = (uint32_t)count;
    a[2] = (uint32_t)(uintptr_t)value;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glUniform3iv, 3, bytes);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)count;
  a[2] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 3, value, bytes);
  glw_end(a);
}

void __wrap_glUniform4f(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform4f(location, v0, v1, v2, v3); return; }
  uint32_t *a = glw_begin(GLW_OP_glUniform4f, 5, 0);
  a[0] = (uint32_t)location;
  a[1] = glw_u(v0);
  a[2] = glw_u(v1);
  a[3] = glw_u(v2);
  a[4] = glw_u(v3);
  glw_end(a);
}

void __wrap_glUniform4fv(GLint location, GLsizei count, const GLfloat* value) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform4fv(location, count, value); return; }
  uint32_t bytes = value ? (uint32_t)(count * 16) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glUniform4fv | GLW_SYNC, 3, 0);
    a[0] = (uint32_t)location;
    a[1] = (uint32_t)count;
    a[2] = (uint32_t)(uintptr_t)value;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glUniform4fv, 3, bytes);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)count;
  a[2] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 3, value, bytes);
  glw_end(a);
}

void __wrap_glUniform4i(GLint location, GLint v0, GLint v1, GLint v2, GLint v3) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform4i(location, v0, v1, v2, v3); return; }
  uint32_t *a = glw_begin(GLW_OP_glUniform4i, 5, 0);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)v0;
  a[2] = (uint32_t)v1;
  a[3] = (uint32_t)v2;
  a[4] = (uint32_t)v3;
  glw_end(a);
}

void __wrap_glUniform4iv(GLint location, GLsizei count, const GLint* value) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniform4iv(location, count, value); return; }
  uint32_t bytes = value ? (uint32_t)(count * 16) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glUniform4iv | GLW_SYNC, 3, 0);
    a[0] = (uint32_t)location;
    a[1] = (uint32_t)count;
    a[2] = (uint32_t)(uintptr_t)value;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glUniform4iv, 3, bytes);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)count;
  a[2] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 3, value, bytes);
  glw_end(a);
}

void __wrap_glUniformMatrix2fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniformMatrix2fv(location, count, transpose, value); return; }
  uint32_t bytes = value ? (uint32_t)(count * 16) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glUniformMatrix2fv | GLW_SYNC, 4, 0);
    a[0] = (uint32_t)location;
    a[1] = (uint32_t)count;
    a[2] = (uint32_t)transpose;
    a[3] = (uint32_t)(uintptr_t)value;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glUniformMatrix2fv, 4, bytes);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)count;
  a[2] = (uint32_t)transpose;
  a[3] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 4, value, bytes);
  glw_end(a);
}

void __wrap_glUniformMatrix3fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniformMatrix3fv(location, count, transpose, value); return; }
  uint32_t bytes = value ? (uint32_t)(count * 36) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glUniformMatrix3fv | GLW_SYNC, 4, 0);
    a[0] = (uint32_t)location;
    a[1] = (uint32_t)count;
    a[2] = (uint32_t)transpose;
    a[3] = (uint32_t)(uintptr_t)value;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glUniformMatrix3fv, 4, bytes);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)count;
  a[2] = (uint32_t)transpose;
  a[3] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 4, value, bytes);
  glw_end(a);
}

void __wrap_glUniformMatrix4fv(GLint location, GLsizei count, GLboolean transpose, const GLfloat* value) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glUniformMatrix4fv(location, count, transpose, value); return; }
  uint32_t bytes = value ? (uint32_t)(count * 64) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glUniformMatrix4fv | GLW_SYNC, 4, 0);
    a[0] = (uint32_t)location;
    a[1] = (uint32_t)count;
    a[2] = (uint32_t)transpose;
    a[3] = (uint32_t)(uintptr_t)value;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glUniformMatrix4fv, 4, bytes);
  a[0] = (uint32_t)location;
  a[1] = (uint32_t)count;
  a[2] = (uint32_t)transpose;
  a[3] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 4, value, bytes);
  glw_end(a);
}

GLboolean __wrap_glUnmapBuffer(GLenum target) {
  GLW_PROF(1);
  if (glw_direct()) return __real_glUnmapBuffer(target);
  uint32_t *a = glw_begin(GLW_OP_glUnmapBuffer | GLW_SYNC, 1, 0);
  a[0] = (uint32_t)target;
  return (GLboolean)(uintptr_t)glw_sync(a);
}

void __wrap_glVertexAttrib1f(GLuint index, GLfloat v0) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glVertexAttrib1f(index, v0); return; }
  uint32_t *a = glw_begin(GLW_OP_glVertexAttrib1f, 2, 0);
  a[0] = (uint32_t)index;
  a[1] = glw_u(v0);
  glw_end(a);
}

void __wrap_glVertexAttrib1fv(GLuint index, const GLfloat* v) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glVertexAttrib1fv(index, v); return; }
  uint32_t bytes = v ? (uint32_t)(4) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glVertexAttrib1fv | GLW_SYNC, 2, 0);
    a[0] = (uint32_t)index;
    a[1] = (uint32_t)(uintptr_t)v;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glVertexAttrib1fv, 2, bytes);
  a[0] = (uint32_t)index;
  a[1] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 2, v, bytes);
  glw_end(a);
}

void __wrap_glVertexAttrib2f(GLuint index, GLfloat v0, GLfloat v1) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glVertexAttrib2f(index, v0, v1); return; }
  uint32_t *a = glw_begin(GLW_OP_glVertexAttrib2f, 3, 0);
  a[0] = (uint32_t)index;
  a[1] = glw_u(v0);
  a[2] = glw_u(v1);
  glw_end(a);
}

void __wrap_glVertexAttrib2fv(GLuint index, const GLfloat* v) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glVertexAttrib2fv(index, v); return; }
  uint32_t bytes = v ? (uint32_t)(8) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glVertexAttrib2fv | GLW_SYNC, 2, 0);
    a[0] = (uint32_t)index;
    a[1] = (uint32_t)(uintptr_t)v;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glVertexAttrib2fv, 2, bytes);
  a[0] = (uint32_t)index;
  a[1] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 2, v, bytes);
  glw_end(a);
}

void __wrap_glVertexAttrib3f(GLuint index, GLfloat v0, GLfloat v1, GLfloat v2) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glVertexAttrib3f(index, v0, v1, v2); return; }
  uint32_t *a = glw_begin(GLW_OP_glVertexAttrib3f, 4, 0);
  a[0] = (uint32_t)index;
  a[1] = glw_u(v0);
  a[2] = glw_u(v1);
  a[3] = glw_u(v2);
  glw_end(a);
}

void __wrap_glVertexAttrib3fv(GLuint index, const GLfloat* v) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glVertexAttrib3fv(index, v); return; }
  uint32_t bytes = v ? (uint32_t)(12) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glVertexAttrib3fv | GLW_SYNC, 2, 0);
    a[0] = (uint32_t)index;
    a[1] = (uint32_t)(uintptr_t)v;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glVertexAttrib3fv, 2, bytes);
  a[0] = (uint32_t)index;
  a[1] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 2, v, bytes);
  glw_end(a);
}

void __wrap_glVertexAttrib4f(GLuint index, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glVertexAttrib4f(index, v0, v1, v2, v3); return; }
  uint32_t *a = glw_begin(GLW_OP_glVertexAttrib4f, 5, 0);
  a[0] = (uint32_t)index;
  a[1] = glw_u(v0);
  a[2] = glw_u(v1);
  a[3] = glw_u(v2);
  a[4] = glw_u(v3);
  glw_end(a);
}

void __wrap_glVertexAttrib4fv(GLuint index, const GLfloat* v) {
  GLW_PROF(1);
  if (glw_direct()) { __real_glVertexAttrib4fv(index, v); return; }
  uint32_t bytes = v ? (uint32_t)(16) : 0;
  if (bytes > GLW_INLINE_MAX) {
    uint32_t *a = glw_begin(GLW_OP_glVertexAttrib4fv | GLW_SYNC, 2, 0);
    a[0] = (uint32_t)index;
    a[1] = (uint32_t)(uintptr_t)v;
    (void)glw_sync(a);
    return;
  }
  uint32_t *a = glw_begin(GLW_OP_glVertexAttrib4fv, 2, bytes);
  a[0] = (uint32_t)index;
  a[1] = bytes ? 1u : 0u;
  if (bytes) memcpy(a + 2, v, bytes);
  glw_end(a);
}

GLboolean __wrap_vglInit(int legacy_pool_size) {
  GLW_PROF(1);
  if (glw_direct()) return __real_vglInit(legacy_pool_size);
  uint32_t *a = glw_begin(GLW_OP_vglInit | GLW_SYNC, 1, 0);
  a[0] = (uint32_t)legacy_pool_size;
  return (GLboolean)(uintptr_t)glw_sync(a);
}

GLboolean __wrap_vglInitExtended(int legacy_pool_size, int width, int height, int ram_threshold, SceGxmMultisampleMode msaa) {
  GLW_PROF(1);
  if (glw_direct()) return __real_vglInitExtended(legacy_pool_size, width, height, ram_threshold, msaa);
  uint32_t *a = glw_begin(GLW_OP_vglInitExtended | GLW_SYNC, 5, 0);
  a[0] = (uint32_t)legacy_pool_size;
  a[1] = (uint32_t)width;
  a[2] = (uint32_t)height;
  a[3] = (uint32_t)ram_threshold;
  a[4] = (uint32_t)msaa;
  return (GLboolean)(uintptr_t)glw_sync(a);
}

void __wrap_vglSetupRuntimeShaderCompiler(shark_opt opt_level, int32_t use_fastmath, int32_t use_fastprecision, int32_t use_fastint) {
  GLW_PROF(1);
  if (glw_direct()) { __real_vglSetupRuntimeShaderCompiler(opt_level, use_fastmath, use_fastprecision, use_fastint); return; }
  uint32_t *a = glw_begin(GLW_OP_vglSetupRuntimeShaderCompiler | GLW_SYNC, 4, 0);
  a[0] = (uint32_t)opt_level;
  a[1] = (uint32_t)use_fastmath;
  a[2] = (uint32_t)use_fastprecision;
  a[3] = (uint32_t)use_fastint;
  (void)glw_sync(a);
}

int glw_replay_gen(uint32_t op, int sync, const uint32_t *a, uint32_t *ret) {
  switch (op) {
  case GLW_OP_glActiveTexture: __real_glActiveTexture((GLenum)a[0]); *ret = 0; return 1;
  case GLW_OP_glAttachShader: __real_glAttachShader((GLuint)a[0], (GLuint)a[1]); *ret = 0; return 1;
  case GLW_OP_glBindAttribLocation: __real_glBindAttribLocation((GLuint)a[0], (GLuint)a[1], (const GLchar*)(sync ? (const void *)(uintptr_t)a[2] : (a[2] ? (const void *)(a + 3) : NULL))); *ret = 0; return 1;
  case GLW_OP_glBindRenderbuffer: __real_glBindRenderbuffer((GLenum)a[0], (GLuint)a[1]); *ret = 0; return 1;
  case GLW_OP_glBindTexture: __real_glBindTexture((GLenum)a[0], (GLuint)a[1]); *ret = 0; return 1;
  case GLW_OP_glBlendEquation: __real_glBlendEquation((GLenum)a[0]); *ret = 0; return 1;
  case GLW_OP_glBlendEquationSeparate: __real_glBlendEquationSeparate((GLenum)a[0], (GLenum)a[1]); *ret = 0; return 1;
  case GLW_OP_glBlendFunc: __real_glBlendFunc((GLenum)a[0], (GLenum)a[1]); *ret = 0; return 1;
  case GLW_OP_glBlendFuncSeparate: __real_glBlendFuncSeparate((GLenum)a[0], (GLenum)a[1], (GLenum)a[2], (GLenum)a[3]); *ret = 0; return 1;
  case GLW_OP_glBufferData: __real_glBufferData((GLenum)a[0], (GLsizei)a[1], (const GLvoid*)(sync ? (const void *)(uintptr_t)a[2] : (a[2] ? (const void *)(a + 4) : NULL)), (GLenum)a[3]); *ret = 0; return 1;
  case GLW_OP_glBufferSubData: __real_glBufferSubData((GLenum)a[0], (GLintptr)a[1], (GLsizeiptr)a[2], (const void*)(sync ? (const void *)(uintptr_t)a[3] : (a[3] ? (const void *)(a + 4) : NULL))); *ret = 0; return 1;
  case GLW_OP_glCheckFramebufferStatus: *ret = (uint32_t)(uintptr_t)__real_glCheckFramebufferStatus((GLenum)a[0]); return 1;
  case GLW_OP_glClear: __real_glClear((GLbitfield)a[0]); *ret = 0; return 1;
  case GLW_OP_glClearColor: __real_glClearColor(glw_f(a[0]), glw_f(a[1]), glw_f(a[2]), glw_f(a[3])); *ret = 0; return 1;
  case GLW_OP_glClearDepthf: __real_glClearDepthf(glw_f(a[0])); *ret = 0; return 1;
  case GLW_OP_glClearStencil: __real_glClearStencil((GLint)a[0]); *ret = 0; return 1;
  case GLW_OP_glColor4f: __real_glColor4f(glw_f(a[0]), glw_f(a[1]), glw_f(a[2]), glw_f(a[3])); *ret = 0; return 1;
  case GLW_OP_glColorMask: __real_glColorMask((GLboolean)a[0], (GLboolean)a[1], (GLboolean)a[2], (GLboolean)a[3]); *ret = 0; return 1;
  case GLW_OP_glCompileShader: __real_glCompileShader((GLuint)a[0]); *ret = 0; return 1;
  case GLW_OP_glCompressedTexImage2D: __real_glCompressedTexImage2D((GLenum)a[0], (GLint)a[1], (GLenum)a[2], (GLsizei)a[3], (GLsizei)a[4], (GLint)a[5], (GLsizei)a[6], (const void*)(sync ? (const void *)(uintptr_t)a[7] : (a[7] ? (const void *)(a + 8) : NULL))); *ret = 0; return 1;
  case GLW_OP_glCopyTexImage2D: __real_glCopyTexImage2D((GLenum)a[0], (GLint)a[1], (GLenum)a[2], (GLint)a[3], (GLint)a[4], (GLsizei)a[5], (GLsizei)a[6], (GLint)a[7]); *ret = 0; return 1;
  case GLW_OP_glCopyTexSubImage2D: __real_glCopyTexSubImage2D((GLenum)a[0], (GLint)a[1], (GLint)a[2], (GLint)a[3], (GLint)a[4], (GLint)a[5], (GLsizei)a[6], (GLsizei)a[7]); *ret = 0; return 1;
  case GLW_OP_glCreateShader: *ret = (uint32_t)(uintptr_t)__real_glCreateShader((GLenum)a[0]); return 1;
  case GLW_OP_glCullFace: __real_glCullFace((GLenum)a[0]); *ret = 0; return 1;
  case GLW_OP_glDeleteFramebuffers: __real_glDeleteFramebuffers((GLsizei)a[0], (const GLuint*)(sync ? (const void *)(uintptr_t)a[1] : (a[1] ? (const void *)(a + 2) : NULL))); *ret = 0; return 1;
  case GLW_OP_glDeleteRenderbuffers: __real_glDeleteRenderbuffers((GLsizei)a[0], (const GLuint*)(sync ? (const void *)(uintptr_t)a[1] : (a[1] ? (const void *)(a + 2) : NULL))); *ret = 0; return 1;
  case GLW_OP_glDeleteShader: __real_glDeleteShader((GLuint)a[0]); *ret = 0; return 1;
  case GLW_OP_glDeleteTextures: __real_glDeleteTextures((GLsizei)a[0], (const GLuint*)(sync ? (const void *)(uintptr_t)a[1] : (a[1] ? (const void *)(a + 2) : NULL))); *ret = 0; return 1;
  case GLW_OP_glDepthFunc: __real_glDepthFunc((GLenum)a[0]); *ret = 0; return 1;
  case GLW_OP_glDepthMask: __real_glDepthMask((GLboolean)a[0]); *ret = 0; return 1;
  case GLW_OP_glDepthRangef: __real_glDepthRangef(glw_f(a[0]), glw_f(a[1])); *ret = 0; return 1;
  case GLW_OP_glFinish: __real_glFinish(); *ret = 0; return 1;
  case GLW_OP_glFlush: __real_glFlush(); *ret = 0; return 1;
  case GLW_OP_glFramebufferRenderbuffer: __real_glFramebufferRenderbuffer((GLenum)a[0], (GLenum)a[1], (GLenum)a[2], (GLuint)a[3]); *ret = 0; return 1;
  case GLW_OP_glFramebufferTexture2D: __real_glFramebufferTexture2D((GLenum)a[0], (GLenum)a[1], (GLenum)a[2], (GLuint)a[3], (GLint)a[4]); *ret = 0; return 1;
  case GLW_OP_glFrontFace: __real_glFrontFace((GLenum)a[0]); *ret = 0; return 1;
  case GLW_OP_glGenBuffers: __real_glGenBuffers((GLsizei)a[0], (GLuint*)(uintptr_t)a[1]); *ret = 0; return 1;
  case GLW_OP_glGenFramebuffers: __real_glGenFramebuffers((GLsizei)a[0], (GLuint*)(uintptr_t)a[1]); *ret = 0; return 1;
  case GLW_OP_glGenRenderbuffers: __real_glGenRenderbuffers((GLsizei)a[0], (GLuint*)(uintptr_t)a[1]); *ret = 0; return 1;
  case GLW_OP_glGenTextures: __real_glGenTextures((GLsizei)a[0], (GLuint*)(uintptr_t)a[1]); *ret = 0; return 1;
  case GLW_OP_glGenerateMipmap: __real_glGenerateMipmap((GLenum)a[0]); *ret = 0; return 1;
  case GLW_OP_glGetActiveAttrib: __real_glGetActiveAttrib((GLuint)a[0], (GLuint)a[1], (GLsizei)a[2], (GLsizei*)(uintptr_t)a[3], (GLint*)(uintptr_t)a[4], (GLenum*)(uintptr_t)a[5], (GLchar*)(uintptr_t)a[6]); *ret = 0; return 1;
  case GLW_OP_glGetActiveUniform: __real_glGetActiveUniform((GLuint)a[0], (GLuint)a[1], (GLsizei)a[2], (GLsizei*)(uintptr_t)a[3], (GLint*)(uintptr_t)a[4], (GLenum*)(uintptr_t)a[5], (GLchar*)(uintptr_t)a[6]); *ret = 0; return 1;
  case GLW_OP_glGetAttachedShaders: __real_glGetAttachedShaders((GLuint)a[0], (GLsizei)a[1], (GLsizei*)(uintptr_t)a[2], (GLuint*)(uintptr_t)a[3]); *ret = 0; return 1;
  case GLW_OP_glGetAttribLocation: *ret = (uint32_t)(uintptr_t)__real_glGetAttribLocation((GLuint)a[0], (const GLchar*)(uintptr_t)a[1]); return 1;
  case GLW_OP_glGetBooleanv: __real_glGetBooleanv((GLenum)a[0], (GLboolean*)(uintptr_t)a[1]); *ret = 0; return 1;
  case GLW_OP_glGetBufferParameteriv: __real_glGetBufferParameteriv((GLenum)a[0], (GLenum)a[1], (GLint*)(uintptr_t)a[2]); *ret = 0; return 1;
  case GLW_OP_glGetFloatv: __real_glGetFloatv((GLenum)a[0], (GLfloat*)(uintptr_t)a[1]); *ret = 0; return 1;
  case GLW_OP_glGetFramebufferAttachmentParameteriv: __real_glGetFramebufferAttachmentParameteriv((GLenum)a[0], (GLenum)a[1], (GLenum)a[2], (GLint*)(uintptr_t)a[3]); *ret = 0; return 1;
  case GLW_OP_glGetProgramInfoLog: __real_glGetProgramInfoLog((GLuint)a[0], (GLsizei)a[1], (GLsizei*)(uintptr_t)a[2], (GLchar*)(uintptr_t)a[3]); *ret = 0; return 1;
  case GLW_OP_glGetProgramiv: __real_glGetProgramiv((GLuint)a[0], (GLenum)a[1], (GLint*)(uintptr_t)a[2]); *ret = 0; return 1;
  case GLW_OP_glGetShaderInfoLog: __real_glGetShaderInfoLog((GLuint)a[0], (GLsizei)a[1], (GLsizei*)(uintptr_t)a[2], (GLchar*)(uintptr_t)a[3]); *ret = 0; return 1;
  case GLW_OP_glGetShaderSource: __real_glGetShaderSource((GLuint)a[0], (GLsizei)a[1], (GLsizei*)(uintptr_t)a[2], (GLchar*)(uintptr_t)a[3]); *ret = 0; return 1;
  case GLW_OP_glGetShaderiv: __real_glGetShaderiv((GLuint)a[0], (GLenum)a[1], (GLint*)(uintptr_t)a[2]); *ret = 0; return 1;
  case GLW_OP_glGetString: *ret = (uint32_t)(uintptr_t)__real_glGetString((GLenum)a[0]); return 1;
  case GLW_OP_glGetUniformLocation: *ret = (uint32_t)(uintptr_t)__real_glGetUniformLocation((GLuint)a[0], (const GLchar*)(uintptr_t)a[1]); return 1;
  case GLW_OP_glGetVertexAttribPointerv: __real_glGetVertexAttribPointerv((GLuint)a[0], (GLenum)a[1], (void**)(uintptr_t)a[2]); *ret = 0; return 1;
  case GLW_OP_glGetVertexAttribfv: __real_glGetVertexAttribfv((GLuint)a[0], (GLenum)a[1], (GLfloat*)(uintptr_t)a[2]); *ret = 0; return 1;
  case GLW_OP_glGetVertexAttribiv: __real_glGetVertexAttribiv((GLuint)a[0], (GLenum)a[1], (GLint*)(uintptr_t)a[2]); *ret = 0; return 1;
  case GLW_OP_glHint: __real_glHint((GLenum)a[0], (GLenum)a[1]); *ret = 0; return 1;
  case GLW_OP_glIsFramebuffer: *ret = (uint32_t)(uintptr_t)__real_glIsFramebuffer((GLuint)a[0]); return 1;
  case GLW_OP_glIsRenderbuffer: *ret = (uint32_t)(uintptr_t)__real_glIsRenderbuffer((GLuint)a[0]); return 1;
  case GLW_OP_glIsTexture: *ret = (uint32_t)(uintptr_t)__real_glIsTexture((GLuint)a[0]); return 1;
  case GLW_OP_glLineWidth: __real_glLineWidth(glw_f(a[0])); *ret = 0; return 1;
  case GLW_OP_glLinkProgram: __real_glLinkProgram((GLuint)a[0]); *ret = 0; return 1;
  case GLW_OP_glMapBuffer: *ret = (uint32_t)(uintptr_t)__real_glMapBuffer((GLenum)a[0], (GLbitfield)a[1]); return 1;
  case GLW_OP_glPolygonOffset: __real_glPolygonOffset(glw_f(a[0]), glw_f(a[1])); *ret = 0; return 1;
  case GLW_OP_glReadPixels: __real_glReadPixels((GLint)a[0], (GLint)a[1], (GLsizei)a[2], (GLsizei)a[3], (GLenum)a[4], (GLenum)a[5], (GLvoid*)(uintptr_t)a[6]); *ret = 0; return 1;
  case GLW_OP_glRenderbufferStorage: __real_glRenderbufferStorage((GLenum)a[0], (GLenum)a[1], (GLsizei)a[2], (GLsizei)a[3]); *ret = 0; return 1;
  case GLW_OP_glShaderBinary: __real_glShaderBinary((GLsizei)a[0], (const GLuint*)(uintptr_t)a[1], (GLenum)a[2], (const void*)(uintptr_t)a[3], (GLsizei)a[4]); *ret = 0; return 1;
  case GLW_OP_glShaderSource: __real_glShaderSource((GLuint)a[0], (GLsizei)a[1], (const GLchar*const*)(uintptr_t)a[2], (const GLint*)(uintptr_t)a[3]); *ret = 0; return 1;
  case GLW_OP_glStencilFunc: __real_glStencilFunc((GLenum)a[0], (GLint)a[1], (GLuint)a[2]); *ret = 0; return 1;
  case GLW_OP_glStencilFuncSeparate: __real_glStencilFuncSeparate((GLenum)a[0], (GLenum)a[1], (GLint)a[2], (GLuint)a[3]); *ret = 0; return 1;
  case GLW_OP_glStencilMask: __real_glStencilMask((GLuint)a[0]); *ret = 0; return 1;
  case GLW_OP_glStencilMaskSeparate: __real_glStencilMaskSeparate((GLenum)a[0], (GLuint)a[1]); *ret = 0; return 1;
  case GLW_OP_glStencilOp: __real_glStencilOp((GLenum)a[0], (GLenum)a[1], (GLenum)a[2]); *ret = 0; return 1;
  case GLW_OP_glStencilOpSeparate: __real_glStencilOpSeparate((GLenum)a[0], (GLenum)a[1], (GLenum)a[2], (GLenum)a[3]); *ret = 0; return 1;
  case GLW_OP_glTexImage2D: __real_glTexImage2D((GLenum)a[0], (GLint)a[1], (GLint)a[2], (GLsizei)a[3], (GLsizei)a[4], (GLint)a[5], (GLenum)a[6], (GLenum)a[7], (const GLvoid*)(sync ? (const void *)(uintptr_t)a[8] : (a[8] ? (const void *)(a + 9) : NULL))); *ret = 0; return 1;
  case GLW_OP_glTexParameterf: __real_glTexParameterf((GLenum)a[0], (GLenum)a[1], glw_f(a[2])); *ret = 0; return 1;
  case GLW_OP_glTexParameteri: __real_glTexParameteri((GLenum)a[0], (GLenum)a[1], (GLint)a[2]); *ret = 0; return 1;
  case GLW_OP_glTexParameteriv: __real_glTexParameteriv((GLenum)a[0], (GLenum)a[1], (GLint*)(sync ? (const void *)(uintptr_t)a[2] : (a[2] ? (const void *)(a + 3) : NULL))); *ret = 0; return 1;
  case GLW_OP_glTexSubImage2D: __real_glTexSubImage2D((GLenum)a[0], (GLint)a[1], (GLint)a[2], (GLint)a[3], (GLsizei)a[4], (GLsizei)a[5], (GLenum)a[6], (GLenum)a[7], (const GLvoid*)(sync ? (const void *)(uintptr_t)a[8] : (a[8] ? (const void *)(a + 9) : NULL))); *ret = 0; return 1;
  case GLW_OP_glUniform1f: __real_glUniform1f((GLint)a[0], glw_f(a[1])); *ret = 0; return 1;
  case GLW_OP_glUniform1fv: __real_glUniform1fv((GLint)a[0], (GLsizei)a[1], (const GLfloat*)(sync ? (const void *)(uintptr_t)a[2] : (a[2] ? (const void *)(a + 3) : NULL))); *ret = 0; return 1;
  case GLW_OP_glUniform1i: __real_glUniform1i((GLint)a[0], (GLint)a[1]); *ret = 0; return 1;
  case GLW_OP_glUniform1iv: __real_glUniform1iv((GLint)a[0], (GLsizei)a[1], (const GLint*)(sync ? (const void *)(uintptr_t)a[2] : (a[2] ? (const void *)(a + 3) : NULL))); *ret = 0; return 1;
  case GLW_OP_glUniform2f: __real_glUniform2f((GLint)a[0], glw_f(a[1]), glw_f(a[2])); *ret = 0; return 1;
  case GLW_OP_glUniform2fv: __real_glUniform2fv((GLint)a[0], (GLsizei)a[1], (const GLfloat*)(sync ? (const void *)(uintptr_t)a[2] : (a[2] ? (const void *)(a + 3) : NULL))); *ret = 0; return 1;
  case GLW_OP_glUniform2i: __real_glUniform2i((GLint)a[0], (GLint)a[1], (GLint)a[2]); *ret = 0; return 1;
  case GLW_OP_glUniform2iv: __real_glUniform2iv((GLint)a[0], (GLsizei)a[1], (const GLint*)(sync ? (const void *)(uintptr_t)a[2] : (a[2] ? (const void *)(a + 3) : NULL))); *ret = 0; return 1;
  case GLW_OP_glUniform3f: __real_glUniform3f((GLint)a[0], glw_f(a[1]), glw_f(a[2]), glw_f(a[3])); *ret = 0; return 1;
  case GLW_OP_glUniform3fv: __real_glUniform3fv((GLint)a[0], (GLsizei)a[1], (const GLfloat*)(sync ? (const void *)(uintptr_t)a[2] : (a[2] ? (const void *)(a + 3) : NULL))); *ret = 0; return 1;
  case GLW_OP_glUniform3i: __real_glUniform3i((GLint)a[0], (GLint)a[1], (GLint)a[2], (GLint)a[3]); *ret = 0; return 1;
  case GLW_OP_glUniform3iv: __real_glUniform3iv((GLint)a[0], (GLsizei)a[1], (const GLint*)(sync ? (const void *)(uintptr_t)a[2] : (a[2] ? (const void *)(a + 3) : NULL))); *ret = 0; return 1;
  case GLW_OP_glUniform4f: __real_glUniform4f((GLint)a[0], glw_f(a[1]), glw_f(a[2]), glw_f(a[3]), glw_f(a[4])); *ret = 0; return 1;
  case GLW_OP_glUniform4fv: __real_glUniform4fv((GLint)a[0], (GLsizei)a[1], (const GLfloat*)(sync ? (const void *)(uintptr_t)a[2] : (a[2] ? (const void *)(a + 3) : NULL))); *ret = 0; return 1;
  case GLW_OP_glUniform4i: __real_glUniform4i((GLint)a[0], (GLint)a[1], (GLint)a[2], (GLint)a[3], (GLint)a[4]); *ret = 0; return 1;
  case GLW_OP_glUniform4iv: __real_glUniform4iv((GLint)a[0], (GLsizei)a[1], (const GLint*)(sync ? (const void *)(uintptr_t)a[2] : (a[2] ? (const void *)(a + 3) : NULL))); *ret = 0; return 1;
  case GLW_OP_glUniformMatrix2fv: __real_glUniformMatrix2fv((GLint)a[0], (GLsizei)a[1], (GLboolean)a[2], (const GLfloat*)(sync ? (const void *)(uintptr_t)a[3] : (a[3] ? (const void *)(a + 4) : NULL))); *ret = 0; return 1;
  case GLW_OP_glUniformMatrix3fv: __real_glUniformMatrix3fv((GLint)a[0], (GLsizei)a[1], (GLboolean)a[2], (const GLfloat*)(sync ? (const void *)(uintptr_t)a[3] : (a[3] ? (const void *)(a + 4) : NULL))); *ret = 0; return 1;
  case GLW_OP_glUniformMatrix4fv: __real_glUniformMatrix4fv((GLint)a[0], (GLsizei)a[1], (GLboolean)a[2], (const GLfloat*)(sync ? (const void *)(uintptr_t)a[3] : (a[3] ? (const void *)(a + 4) : NULL))); *ret = 0; return 1;
  case GLW_OP_glUnmapBuffer: *ret = (uint32_t)(uintptr_t)__real_glUnmapBuffer((GLenum)a[0]); return 1;
  case GLW_OP_glVertexAttrib1f: __real_glVertexAttrib1f((GLuint)a[0], glw_f(a[1])); *ret = 0; return 1;
  case GLW_OP_glVertexAttrib1fv: __real_glVertexAttrib1fv((GLuint)a[0], (const GLfloat*)(sync ? (const void *)(uintptr_t)a[1] : (a[1] ? (const void *)(a + 2) : NULL))); *ret = 0; return 1;
  case GLW_OP_glVertexAttrib2f: __real_glVertexAttrib2f((GLuint)a[0], glw_f(a[1]), glw_f(a[2])); *ret = 0; return 1;
  case GLW_OP_glVertexAttrib2fv: __real_glVertexAttrib2fv((GLuint)a[0], (const GLfloat*)(sync ? (const void *)(uintptr_t)a[1] : (a[1] ? (const void *)(a + 2) : NULL))); *ret = 0; return 1;
  case GLW_OP_glVertexAttrib3f: __real_glVertexAttrib3f((GLuint)a[0], glw_f(a[1]), glw_f(a[2]), glw_f(a[3])); *ret = 0; return 1;
  case GLW_OP_glVertexAttrib3fv: __real_glVertexAttrib3fv((GLuint)a[0], (const GLfloat*)(sync ? (const void *)(uintptr_t)a[1] : (a[1] ? (const void *)(a + 2) : NULL))); *ret = 0; return 1;
  case GLW_OP_glVertexAttrib4f: __real_glVertexAttrib4f((GLuint)a[0], glw_f(a[1]), glw_f(a[2]), glw_f(a[3]), glw_f(a[4])); *ret = 0; return 1;
  case GLW_OP_glVertexAttrib4fv: __real_glVertexAttrib4fv((GLuint)a[0], (const GLfloat*)(sync ? (const void *)(uintptr_t)a[1] : (a[1] ? (const void *)(a + 2) : NULL))); *ret = 0; return 1;
  case GLW_OP_vglInit: *ret = (uint32_t)(uintptr_t)__real_vglInit((int)a[0]); return 1;
  case GLW_OP_vglInitExtended: *ret = (uint32_t)(uintptr_t)__real_vglInitExtended((int)a[0], (int)a[1], (int)a[2], (int)a[3], (SceGxmMultisampleMode)a[4]); return 1;
  case GLW_OP_vglSetupRuntimeShaderCompiler: __real_vglSetupRuntimeShaderCompiler((shark_opt)a[0], (int32_t)a[1], (int32_t)a[2], (int32_t)a[3]); *ret = 0; return 1;
  default: return 0;
  }
}

extern void __wrap_glBeginQuery(GLenum target, GLuint id);
extern void __wrap_glBindBuffer(GLenum target, GLuint buffer);
extern void __wrap_glBindFramebuffer(GLenum target, GLuint framebuffer);
extern GLuint __wrap_glCreateProgram(void);
extern void __wrap_glDeleteBuffers(GLsizei n, const GLuint* gl_buffers);
extern void __wrap_glDeleteProgram(GLuint prog);
extern void __wrap_glDisable(GLenum cap);
extern void __wrap_glDisableClientState(GLenum array);
extern void __wrap_glDisableVertexAttribArray(GLuint index);
extern void __wrap_glDrawArrays(GLenum mode, GLint first, GLsizei count);
extern void __wrap_glDrawElements(GLenum mode, GLsizei count, GLenum type, const GLvoid* indices);
extern void __wrap_glEnable(GLenum cap);
extern void __wrap_glEnableClientState(GLenum array);
extern void __wrap_glEnableVertexAttribArray(GLuint index);
extern void __wrap_glEndQuery(GLenum target);
extern void __wrap_glGenQueries(GLsizei n, GLuint* ids);
extern GLenum __wrap_glGetError(void);
extern void __wrap_glGetIntegerv(GLenum pname, GLint* data);
extern void __wrap_glGetQueryObjectuiv(GLuint id, GLenum pname, GLuint* params);
extern GLboolean __wrap_glIsEnabled(GLenum cap);
extern GLboolean __wrap_glIsProgram(GLuint program);
extern void __wrap_glPixelStorei(GLenum pname, GLint param);
extern void __wrap_glScissor(GLint x, GLint y, GLsizei width, GLsizei height);
extern void __wrap_glTexCoordPointer(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer);
extern void __wrap_glUseProgram(GLuint program);
extern void __wrap_glVertexAttribPointer(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void* pointer);
extern void __wrap_glVertexPointer(GLint size, GLenum type, GLsizei stride, const GLvoid* pointer);
extern void __wrap_glViewport(GLint x, GLint y, GLsizei width, GLsizei height);
extern void * __wrap_vglGetProcAddress(const char* name);
extern void __wrap_vglSwapBuffers(GLboolean has_commondialog);
const glw_proc_t glw_procs[] = {
  {"glActiveTexture", (void *)__wrap_glActiveTexture},
  {"glAttachShader", (void *)__wrap_glAttachShader},
  {"glBeginQuery", (void *)__wrap_glBeginQuery},
  {"glBindAttribLocation", (void *)__wrap_glBindAttribLocation},
  {"glBindBuffer", (void *)__wrap_glBindBuffer},
  {"glBindFramebuffer", (void *)__wrap_glBindFramebuffer},
  {"glBindRenderbuffer", (void *)__wrap_glBindRenderbuffer},
  {"glBindTexture", (void *)__wrap_glBindTexture},
  {"glBlendEquation", (void *)__wrap_glBlendEquation},
  {"glBlendEquationSeparate", (void *)__wrap_glBlendEquationSeparate},
  {"glBlendFunc", (void *)__wrap_glBlendFunc},
  {"glBlendFuncSeparate", (void *)__wrap_glBlendFuncSeparate},
  {"glBufferData", (void *)__wrap_glBufferData},
  {"glBufferSubData", (void *)__wrap_glBufferSubData},
  {"glCheckFramebufferStatus", (void *)__wrap_glCheckFramebufferStatus},
  {"glClear", (void *)__wrap_glClear},
  {"glClearColor", (void *)__wrap_glClearColor},
  {"glClearDepthf", (void *)__wrap_glClearDepthf},
  {"glClearStencil", (void *)__wrap_glClearStencil},
  {"glColor4f", (void *)__wrap_glColor4f},
  {"glColorMask", (void *)__wrap_glColorMask},
  {"glCompileShader", (void *)__wrap_glCompileShader},
  {"glCompressedTexImage2D", (void *)__wrap_glCompressedTexImage2D},
  {"glCopyTexImage2D", (void *)__wrap_glCopyTexImage2D},
  {"glCopyTexSubImage2D", (void *)__wrap_glCopyTexSubImage2D},
  {"glCreateProgram", (void *)__wrap_glCreateProgram},
  {"glCreateShader", (void *)__wrap_glCreateShader},
  {"glCullFace", (void *)__wrap_glCullFace},
  {"glDeleteBuffers", (void *)__wrap_glDeleteBuffers},
  {"glDeleteFramebuffers", (void *)__wrap_glDeleteFramebuffers},
  {"glDeleteProgram", (void *)__wrap_glDeleteProgram},
  {"glDeleteRenderbuffers", (void *)__wrap_glDeleteRenderbuffers},
  {"glDeleteShader", (void *)__wrap_glDeleteShader},
  {"glDeleteTextures", (void *)__wrap_glDeleteTextures},
  {"glDepthFunc", (void *)__wrap_glDepthFunc},
  {"glDepthMask", (void *)__wrap_glDepthMask},
  {"glDepthRangef", (void *)__wrap_glDepthRangef},
  {"glDisable", (void *)__wrap_glDisable},
  {"glDisableClientState", (void *)__wrap_glDisableClientState},
  {"glDisableVertexAttribArray", (void *)__wrap_glDisableVertexAttribArray},
  {"glDrawArrays", (void *)__wrap_glDrawArrays},
  {"glDrawElements", (void *)__wrap_glDrawElements},
  {"glEnable", (void *)__wrap_glEnable},
  {"glEnableClientState", (void *)__wrap_glEnableClientState},
  {"glEnableVertexAttribArray", (void *)__wrap_glEnableVertexAttribArray},
  {"glEndQuery", (void *)__wrap_glEndQuery},
  {"glFinish", (void *)__wrap_glFinish},
  {"glFlush", (void *)__wrap_glFlush},
  {"glFramebufferRenderbuffer", (void *)__wrap_glFramebufferRenderbuffer},
  {"glFramebufferTexture2D", (void *)__wrap_glFramebufferTexture2D},
  {"glFrontFace", (void *)__wrap_glFrontFace},
  {"glGenBuffers", (void *)__wrap_glGenBuffers},
  {"glGenFramebuffers", (void *)__wrap_glGenFramebuffers},
  {"glGenQueries", (void *)__wrap_glGenQueries},
  {"glGenRenderbuffers", (void *)__wrap_glGenRenderbuffers},
  {"glGenTextures", (void *)__wrap_glGenTextures},
  {"glGenerateMipmap", (void *)__wrap_glGenerateMipmap},
  {"glGetActiveAttrib", (void *)__wrap_glGetActiveAttrib},
  {"glGetActiveUniform", (void *)__wrap_glGetActiveUniform},
  {"glGetAttachedShaders", (void *)__wrap_glGetAttachedShaders},
  {"glGetAttribLocation", (void *)__wrap_glGetAttribLocation},
  {"glGetBooleanv", (void *)__wrap_glGetBooleanv},
  {"glGetBufferParameteriv", (void *)__wrap_glGetBufferParameteriv},
  {"glGetError", (void *)__wrap_glGetError},
  {"glGetFloatv", (void *)__wrap_glGetFloatv},
  {"glGetFramebufferAttachmentParameteriv", (void *)__wrap_glGetFramebufferAttachmentParameteriv},
  {"glGetIntegerv", (void *)__wrap_glGetIntegerv},
  {"glGetProgramInfoLog", (void *)__wrap_glGetProgramInfoLog},
  {"glGetProgramiv", (void *)__wrap_glGetProgramiv},
  {"glGetQueryObjectuiv", (void *)__wrap_glGetQueryObjectuiv},
  {"glGetShaderInfoLog", (void *)__wrap_glGetShaderInfoLog},
  {"glGetShaderSource", (void *)__wrap_glGetShaderSource},
  {"glGetShaderiv", (void *)__wrap_glGetShaderiv},
  {"glGetString", (void *)__wrap_glGetString},
  {"glGetUniformLocation", (void *)__wrap_glGetUniformLocation},
  {"glGetVertexAttribPointerv", (void *)__wrap_glGetVertexAttribPointerv},
  {"glGetVertexAttribfv", (void *)__wrap_glGetVertexAttribfv},
  {"glGetVertexAttribiv", (void *)__wrap_glGetVertexAttribiv},
  {"glHint", (void *)__wrap_glHint},
  {"glIsEnabled", (void *)__wrap_glIsEnabled},
  {"glIsFramebuffer", (void *)__wrap_glIsFramebuffer},
  {"glIsProgram", (void *)__wrap_glIsProgram},
  {"glIsRenderbuffer", (void *)__wrap_glIsRenderbuffer},
  {"glIsTexture", (void *)__wrap_glIsTexture},
  {"glLineWidth", (void *)__wrap_glLineWidth},
  {"glLinkProgram", (void *)__wrap_glLinkProgram},
  {"glMapBuffer", (void *)__wrap_glMapBuffer},
  {"glPixelStorei", (void *)__wrap_glPixelStorei},
  {"glPolygonOffset", (void *)__wrap_glPolygonOffset},
  {"glReadPixels", (void *)__wrap_glReadPixels},
  {"glRenderbufferStorage", (void *)__wrap_glRenderbufferStorage},
  {"glScissor", (void *)__wrap_glScissor},
  {"glShaderBinary", (void *)__wrap_glShaderBinary},
  {"glShaderSource", (void *)__wrap_glShaderSource},
  {"glStencilFunc", (void *)__wrap_glStencilFunc},
  {"glStencilFuncSeparate", (void *)__wrap_glStencilFuncSeparate},
  {"glStencilMask", (void *)__wrap_glStencilMask},
  {"glStencilMaskSeparate", (void *)__wrap_glStencilMaskSeparate},
  {"glStencilOp", (void *)__wrap_glStencilOp},
  {"glStencilOpSeparate", (void *)__wrap_glStencilOpSeparate},
  {"glTexCoordPointer", (void *)__wrap_glTexCoordPointer},
  {"glTexImage2D", (void *)__wrap_glTexImage2D},
  {"glTexParameterf", (void *)__wrap_glTexParameterf},
  {"glTexParameteri", (void *)__wrap_glTexParameteri},
  {"glTexParameteriv", (void *)__wrap_glTexParameteriv},
  {"glTexSubImage2D", (void *)__wrap_glTexSubImage2D},
  {"glUniform1f", (void *)__wrap_glUniform1f},
  {"glUniform1fv", (void *)__wrap_glUniform1fv},
  {"glUniform1i", (void *)__wrap_glUniform1i},
  {"glUniform1iv", (void *)__wrap_glUniform1iv},
  {"glUniform2f", (void *)__wrap_glUniform2f},
  {"glUniform2fv", (void *)__wrap_glUniform2fv},
  {"glUniform2i", (void *)__wrap_glUniform2i},
  {"glUniform2iv", (void *)__wrap_glUniform2iv},
  {"glUniform3f", (void *)__wrap_glUniform3f},
  {"glUniform3fv", (void *)__wrap_glUniform3fv},
  {"glUniform3i", (void *)__wrap_glUniform3i},
  {"glUniform3iv", (void *)__wrap_glUniform3iv},
  {"glUniform4f", (void *)__wrap_glUniform4f},
  {"glUniform4fv", (void *)__wrap_glUniform4fv},
  {"glUniform4i", (void *)__wrap_glUniform4i},
  {"glUniform4iv", (void *)__wrap_glUniform4iv},
  {"glUniformMatrix2fv", (void *)__wrap_glUniformMatrix2fv},
  {"glUniformMatrix3fv", (void *)__wrap_glUniformMatrix3fv},
  {"glUniformMatrix4fv", (void *)__wrap_glUniformMatrix4fv},
  {"glUnmapBuffer", (void *)__wrap_glUnmapBuffer},
  {"glUseProgram", (void *)__wrap_glUseProgram},
  {"glVertexAttrib1f", (void *)__wrap_glVertexAttrib1f},
  {"glVertexAttrib1fv", (void *)__wrap_glVertexAttrib1fv},
  {"glVertexAttrib2f", (void *)__wrap_glVertexAttrib2f},
  {"glVertexAttrib2fv", (void *)__wrap_glVertexAttrib2fv},
  {"glVertexAttrib3f", (void *)__wrap_glVertexAttrib3f},
  {"glVertexAttrib3fv", (void *)__wrap_glVertexAttrib3fv},
  {"glVertexAttrib4f", (void *)__wrap_glVertexAttrib4f},
  {"glVertexAttrib4fv", (void *)__wrap_glVertexAttrib4fv},
  {"glVertexAttribPointer", (void *)__wrap_glVertexAttribPointer},
  {"glVertexPointer", (void *)__wrap_glVertexPointer},
  {"glViewport", (void *)__wrap_glViewport},
  {NULL, NULL},
};
